### ISSUE TITLE
Expando property support?

### ISSUE THREAD

**Issue by davidchase** [paldepind/snabbdom#10]
Hey @paldepind really great library.. i use sometimes the [expando](https://developer.mozilla.org/en-US/docs/Glossary/Expando) property and in [virtual-dom](https://github.com/Matt-Esch/virtual-dom) i was able to simply add them when you using `h` and worked fine however i wasnt able to achieve the same results in snabbdom..

do you know if thats expected ?

thanks

**Comment by paldepind** [comment]
Hello!

I'm glad you like the library! How do you feel about it compared to virtual-dom?

Are you using [props](https://github.com/paldepind/snabbdom/blob/master/README.md#the-props-module)? It should not be a problem.

Kind regards

**Comment by davidchase** [comment]
Ahh prefect a small oversight on my part.. I like snabbdom better simply because it conveys a more minimal and modular approach.

**Comment by paldepind** [comment]
> I like snabbdom better simply because it conveys a more minimal and modular approach.

Great! That is exactly the main purpose :)

If you run in to other issues please let me know. Do you have a recommendation on how to make this more obvious in the readme? Maybe I should add a section to people coming from virtual-dom?

**Comment by davidchase** [comment]
I don't know if a lot of people use expando properties.. but you could just give a example in the props section that uses a non DOM specific property thats the only thing that comes to mind.

Again it was also an oversight on my part i was just trying a quick switch and didn't notice the different setup  :disappointed:

**Comment by davidchase** [comment]
I thought about it a little more and i think if you add more examples that can help as well.. examples can show for instance how snabbdom can be rendered from the server and then patched on the client and other practical usage that users can resonate with.. what do think?

**Comment by paldepind** [comment]
>  how snabbdom can be rendered from the server and then patched on the client

I'm not sure what you mean with that?

**Comment by davidchase** [comment]
So with `virtual-dom` and using something like `vdom-to-html` for example i render the contents 1st time from the server and then updates can be done on the client if necessary. mercury has an example of [this](https://github.com/Raynos/mercury/blob/master/examples/server-rendering/server.js).

hopefully that makes a bit more sense, i dont know if had ideas of this project being able to do the same.
