### ISSUE TITLE
classNames in `.sel` and `data.props.className` can't coexist.

### ISSUE THREAD

**Issue by TylorS** [paldepind/snabbdom#103]
Hey, I'm not sure if this is a bug or expected behavior, but I figured I might as well report it and see if it *is* a bug. A user of one of my libraries found this to be counter-intuitive.

Currently when using both a css selector in the first argument to `h()`, and also a `className` to the props module, only the className defined in props will be applied to the DOM node.

e.g.
`h('div.something', {props: { className: 'other' }}, [..])` 

you'll end up with `<div class="other">`, when I'd expect `<div class="something other">`.

Heres a real test case that reproduces the 'bug'. If you inspect the output, you'll see that the `.sel` of the 3rd element is clobbered.
http://esnextb.in/?gist=dd2f6f68f466b1d88088b2d3fbf458e8

**Comment by paldepind** [comment]
Setting `className` on a DOM element always overwrites all existing classes. That is just the way the property works. Just like setting `innerHTML` overwrites all existing content of an element.

If that is not the desired behaviour then one should use a different method for setting classes. Like the classes module.

**Comment by TylorS** [comment]
Thank you, good points!
