### ISSUE TITLE
The new thunk-implementation killed my component-implementation

### ISSUE THREAD

**Issue by kay999** [paldepind/snabbdom#104]
I'm using a simple component implementation based on this code:

```javascript
exports.stateful = function(func) {
	function redraw() {									// patch into stored parent-node
		if (vnode) vnode.data.vnode = patch(vnode.data.vnode, func(redraw));
	}
	let vnode = h('_thunk', { vnode: func(redraw)} );	// init by calling func
	return vnode;
};
```

With this you can easily create components which can redraw them self after changes. For example:

```javascript
function testButton() {
    var state = 0;
    return M.stateful(function(redraw) {
        function incr() {
            state++;
            redraw();
        }
        return h('button', { on:{click:incr} }, "value:" + state)
    });
}
```

which creates a button which increases it's value on each click (the state is obviously reset to 0 if the testButton component is redrawn, but that's intended because it allows to set the state from the outside).

It's based on the old thunk-impl which uses data.vnode to store the current vnode of the component. By calling redraw() this node is then replaced and re-patched into the dom. The same can be archived by using for example a dummy-div node as parent, but this has the big disadvantage that it messes up the dom with dummy nodes (kills nth-child css selectors). So the implementation via data.vnode worked quite well for me.

Is there a way to make this concept (or something similar) work in the new thunk implementation?

**Comment by paldepind** [comment]
I can see your problem. Let me note that this stateful implementation is subject to the same bugs that haunted the thunk implementation.

I think this will work. I haven't tested it.

```js
function setPost(vnode, hook) {
  // set the `postpatch` hook of a node
  // should be made more robust by checking path existence
  vnode.data.hook.postpatch = hook;
}

exports.stateful = function(func) {
  let vnode; // store local vnode
  function redraw() {
    if (vnode !== undefined) {
      vnode.data.hook.postpatch = undefined; // hook should not be called in local patch
      let newVnode = patch(vnode, func(redraw)); // do local patch
      setPost(newVnode, postHook); // install hook in new vnode for future global patch
      _.merge(vnode, newVnode); // merge in new vnode so global patch will use it
    }
  }
  function postHook(oldVnode, newVnode) {
    // we are here due to a global patch that has change our vnode
    vnode = newVnode; // replace local reference to new vnode from global patch
    setPost(vnode, postHook); // install hook in new vnode
  });
  vnode = func(redraw); // Create initial vnode
  setPost(vnode, postHook); // install hook in initial vnode
  return vnode;
}
```

Does that make sense to you?
