### ISSUE TITLE
Raw HTML

### ISSUE THREAD

**Issue by ivan-kleshnin** [paldepind/snabbdom#105]
**virtual-dom** allows to embed HTML through `innerHTML` attribute

```js
h("div", {innerHTML: `<a href="https://github.com/Paqmind/memory-game" target="_blank" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>`})
```

 This is critical for SVG and stuff like that which are extremely painful to convert to hyperscript and support after that. It's much better to keep them as raw HTML. Is it possible to add such feature to **snabbdom**?

**Comment by TylorS** [comment]
This could be done with a module. http://esnextb.in/?gist=f1b4bd682d911950ea192e801bdb59eb

**Comment by kay999** [comment]
I do it simply by using

`h('div', { props: { innerHTML: "..." }})`

**Comment by ivan-kleshnin** [comment]
@TylorS 👍 good idea.

@kay999 ✌️ that works.

I think this should be mentioned in README.

**Comment by rayd** [comment]
Along these lines, I've been working on a library to convert HTML strings to `VNode`s: https://github.com/appcues/snabbdom-virtualize.

**Comment by ivan-kleshnin** [comment]
@rayd for string there are [html-to-hyperscript](https://github.com/ivan-kleshnin/html-to-hyperscript) and some other libs. For DOM nodes (don't see how this useful right now but sounds cool) – no analogy.

**Comment by rayd** [comment]
@ivan-kleshnin very cool! my use case is a little different, as this code is living in a script that we need to keep to the absolute minimum (why I shied away from the parse5 dependency).

**Comment by ivan-kleshnin** [comment]
@rayd thanks. Gave a star to your repo. Good luck!

**Comment by paldepind** [comment]
@rayd, that looks very interesting. What are you using it for? I imagine that it would be useful if one is doing server side rendering initially and wants to use the initial DOM as a basis for further patching.

**Comment by rayd** [comment]
The product I'm working on has some user-generated HTML that's produced on the server-side. We then need to display this content inside of a set of nodes that we construct client-side. So I'm essentially doing something along the lines of (using snabbdom-jsx):
```html
<div classNames="content-panel">
    {virtualize(contentString)}
</div>
```
The nice thing with being able to convert the string into vnodes is that I can perform some modifications, like adding event listeners, to the vnodes of the user-generated `contentString` if I need to. And of course patch the vnodes of the `contentString` as it's interacted with. So far it's working pretty well :smiley:

**Comment by musicode** [comment]
```js
h('div', [ 'content is', 'user-generated HTML' ])
```

how to keep html unescaped?

**Comment by kay999** [comment]
If both should be unesacped:
`h('div', { props: { innerHTML: "content is'" + "user-generated HTML" }})`

Otherwise you need to wrap part of it into a tag:
`h('div', [ 'content is', h('span', { props: { innerHTML: "user-generated HTML" }})])`

**Comment by musicode** [comment]
@kay999 Actually, `span` is not a user generated content. I hope VNode can support raw html, so I can write the code as below:

```
h('div', [ 'content is', new VNode('user-generated HTML') ])
```

**Comment by mightyiam** [comment]
@musicode `new VNode('html')` doesn't make sense to me, because there has to be a containing element. What's wrong with `innerHTML`?

**Comment by musicode** [comment]
@mightyiam Maybe your means the example?

```js
h('div', { props: { innerHTML: "..." }})
```

look at a mustache template:

```html
<div>
    content is: {{{content}}}
</div>
``` 

I need a simple wayto achieve it like this:

```js
h('div', [ 'content is', new VNode(content) ])
```
