### ISSUE TITLE
Provide a standalone file

### ISSUE THREAD

**Issue by Risto-Stevcev** [paldepind/snabbdom#109]
There's currently no way to include this library without browserify or bundling a standlone. It would be nice to have a prebundled version of the library available through git.

And wzrd.in can't be used because `snabbdom` has multiple entry points (ie `snabbdom/h`)

**Comment by paldepind** [comment]
I agree. Creating a build with all the default modules would be useful.

I'd highly appreciate a PR. I'm pretty indifferent with regards to build system/bundler.

**Comment by Risto-Stevcev** [comment]
Sure

**Comment by Risto-Stevcev** [comment]
Added PR #119
