### ISSUE TITLE
partial update

### ISSUE THREAD

**Issue by gaydenko** [paldepind/snabbdom#11]
To continue gitter conversation related to components nesting, I guess it would be extremely handy to add partial update the way it exists in cito.js. In a word, children can be represented as a function, and during redraw pass children's update is skipped if a function returns `undefined`. 

This way it is possible to attach (with `patch`) new absolutely alien and independent vnode (component) to already existing onde. As long as parent vnode exists, it doesn't see children, and the last one has own independent life cycle. 

And this is an application logic and presentation logic separation I have wrote about :)

I guess it would demand minimal code change. Sorry, can not suggest PR as far as didn't grokked a source code yet.

**Comment by paldepind** [comment]
Yes. I'm aware og that feature. I actually read cito.js before I wrote Snabbdom.

I see it as an optimization and Snabbdom achieves the same with thunks.

> This way it is possible to attach (with patch) new absolutely alien and independent vnode (component) to already existing onde.

I don't understand this. You can do that already whenever you want to? That is the part of the idea of diffing and patching vnodes.

**Comment by gaydenko** [comment]
@paldepind , 

> Snabbdom achieves the same with thunks

Are there any hints/examples to understand thunks? I haven't met them, but probably I have missed something.

> I don't understand this. You can do that already whenever you want to? That is the part of the idea of diffing and patching vnodes.

Sorry, I must rethink own mental model of  vdom :) 

It seems, one vdom knows nothing about the fact that another vdom was applied to DOM regardless the actual DOM nodes affected by the second vdom. Is the last thesis valid?

**Comment by ericgj** [comment]
@gaydenko  I believe snabbdom's concept of thunks is adapted from [virtual-dom](https://github.com/Raynos/vdom-thunk/)'s, although the interface is different. Before patching a thunk vnode, it checks if the arguments against the previous arguments, and only re-evaluates if they have changed.  See  https://github.com/paldepind/snabbdom/blob/master/thunk.js . It would be good to have an example of thunks in action, if I have time maybe will add one.  

But as paldepind says, this is an optimization technique, not really related to your point about independence of app logic and presentation logic. That's a bigger discussion I will drop a line about in the gitter room when I have a chance....

**Comment by gaydenko** [comment]
@ericgj , thanks for the hints, the will definitely help to understand.
