### ISSUE TITLE
return new vnode on init hook is broken

### ISSUE THREAD

**Issue by Guria** [paldepind/snabbdom#112]
> If the hook handler sets the vnode property on the vnode, then Snabbdom will use the vnode at vnode instead of the actual vnode.

https://github.com/paldepind/snabbdom#the-init-hook
```js
patch(container, {
  data: { hook: vnode => { vnode.vnode = { sel: 'div', text: 'hello' } } }
})
```
will render 'undefined' as text node in container.

after some source code inspecting (v0.4.2) I have found that new vnode in fact checked on data object:
```js
patch(container, {
  data: { hook: vnode => { vnode.data.vnode = { sel: 'div', text: 'hello' } } }
})
```
but it has caused some internal errors in modules and snabbdom itself

Just updated to 0.5.0 and seems it ignores both ways. It doesn't tries to check vnode.vnode nor vnode.data.vnode existence after init callback invoked. The only way possible here is mutating vnode itself:
```js
patch(container, {
  data: { hook: vnode => { vnode.sel = 'div'; vnode.text = 'hello' }
})
```
Not sure if its a bug or outdated doc.

**Comment by paldepind** [comment]
This is outdated documentation. See #97 and #104. The old behaviour never worked probably. Mutating the `vnode` itself is the solution. This turned out to be the simplest approach overall.

**Comment by paldepind** [comment]
I've now removed the mention of the `vnode` property in the documentation.
