### ISSUE TITLE
isDef()

### ISSUE THREAD

**Issue by gaydenko** [paldepind/snabbdom#12]
Reading the source I have noticed plenty (~60) occurrences of `!isUndef()`. To make code more readable I suggest to replace them with newly introduce `isDef()` one-liner.

**Comment by gaydenko** [comment]
As far as a style is a matter if taste, I guess the issue must be closed.

**Comment by paldepind** [comment]
Thank you for the suggestion. That is a fine idea! 459c46e22 carries it out :)
