### ISSUE TITLE
null / undefined children

### ISSUE THREAD

**Issue by AlexGalays** [paldepind/snabbdom#123]
It's quite convenient to be able to use null or undefined children, e.g:

```javascript
const popup = popupOpened ? popup() : undefined

return h('div', [
  h('p', 'blabla'),
  popup
])
```

virtual-dom and React support that for instance. Would it be a lot of work to add this in ? Would it mess with reconciliation indexes?

**Comment by AlexGalays** [comment]
string children fill that role.

**Comment by grimalschi** [comment]
yeah, const popup = popupOpened ? popup() : ''

**Comment by Hypnosphi** [comment]
What's the problem though to support null/undefined as well?
