### ISSUE TITLE
Support for SVG foreignObject?

### ISSUE THREAD

**Issue by harrywincup** [paldepind/snabbdom#126]
Hi there,

I'm using CycleJS (which just switched to Snabbdom from virtual-dom, I believe) and attempting to use `foreignObject` to render some HTML inside an SVG chart (for a tooltip). However, the content of the foreignObject doesn't display, possibly because all of the children are being set to use the svg namespace instead of the given `http://www.w3.org/1999/xhtml ` (hinted at in https://github.com/cyclejs/core/issues/345) 

Any thoughts on if there's a way to get this working?

```javascript
svg.foreignObject({ attrs: { width: '100', height: '50' }}, [
    body({ attrs: { xmlns: 'http://www.w3.org/1999/xhtml' }}, [
        p('THIS IS A PARAGRAPH THAT CAN WRAP TEXT')
    ])
])
```

Thanks!

**Comment by paldepind** [comment]
Hello @harrywincup. I see you've fixed this issue in Cycle. Would you like to submit a PR to the Snabbdom `h` function as well? Or may I use the changes in your PR to Cycle?

**Comment by harrywincup** [comment]
@paldepind Apologies! I totally forgot to send the same fix to Snabbdom. I've submitted a PR (https://github.com/paldepind/snabbdom/pull/133) so hopefully you can find a moment to review and let me know any changes / improvements required.

Thanks 👍

**Comment by paldepind** [comment]
Thank you for the PR and for solving this issue!
