### ISSUE TITLE
Question about the emptyVnode passed to the first arg of create hooks

### ISSUE THREAD

**Issue by AlexGalays** [paldepind/snabbdom#129]
What's the purpose of this ? It seems to me `create` having the same signature as `insert` would be more straightforward.

**Comment by paldepind** [comment]
It is to have the same signature as as the `update` hook. Thus we can reuse the same function to handle both hooks. This is for instance used in the [style module](https://github.com/paldepind/snabbdom/blob/master/modules/style.js#L69).

**Comment by AlexGalays** [comment]
I see!
