### ISSUE TITLE
The event listening module should support passing several arguments to even handlers

### ISSUE THREAD

**Issue by paldepind** [paldepind/snabbdom#13]
Today the [event listeners module](https://github.com/paldepind/snabbdom#eventlisteners-module) supports passing custom arguments to event handler functions.

```js
function clickHandler(number) { console.log('button ' + number + ' was clicked!'); }
h('div', [
  h('a', {on: {click: [clickHandler, 1]}}),
  h('a', {on: {click: [clickHandler, 2]}}),
  h('a', {on: {click: [clickHandler, 3]}}),
]);
```

However, only one argument is supported. This restriction should be lifted so that a variable amount of arguments is supported.

**Comment by ericgj** [comment]
So  `[handler, a, b, c]`  would be treated as `handler(a,b,c)` ?  Sounds fine to me.  

One thing I was looking to do recently was define multiple **handlers**, but I think that would need to be a separate module (if even advisable at all).

**Comment by paldepind** [comment]
Yes. Exactly.

One solution to needing multiple handlers would be to create a function that invokes both functions. Or a helper function to achieve that. But I'd also be interested in hearing how you think that would look if integrated into Snabbdom in a module?

**Comment by ericgj** [comment]
Yeah, I was considering a helper function like  `multi( [handler1, a], [handler2, b] )`  which compiles down to one handler that runs each in sequence. That seems better than putting two event handlers on the DOM node, thinking about it some more. Do you agree?  

But to give you a sense of the use-case (because maybe there is a more straightforward way of doing it). Consider a submit button that triggers an XHR request. You want your application to indicate the request is in flight (perhaps by disabling the button, or showing a spinner or message, etc.). It seems like the right way to do that here would be to update some flag in your application state when the XHR starts, and then again when the request is done. One way to model this is as _two_ actions in your event handler, one synchronous and one asynchronous, something like:

```js
{ on: { click: multi( [action$, Action.BeforeUpdateThing()], 
                      [task$, Task.UpdateThing(model)] 
                    )
      }  
}
```

(where `Task.UpdateThing` runs the request in a promise, and forwards the response wrapped in an action back to `action$`).

Sorry for hijacking this thread a bit, but thought it might be helpful to understand more of the context of what I'm trying to do. If it makes more sense I can drop this into gitter to discuss it there.

**Comment by yelouafi** [comment]
it seems to me that this concerns should be left out to a functional library; for now i'm just using standard JavaScript functions

for multi-argument i use `bind`
```javascript
h('div', [
  h('a', {on: {click: clickHandler.bind(null, 1, 2) }}),
]);
```
and one nice effect is that i get also the event object if i need it
```javascript
function clickHandler(a1, a2, event) { ... }
```

for the multiple handler question i use a small util function: `sequence` which do function composition but in the inverse order

```javascript
h('div', [
  h('a', {on: {click: sequence( clickHandler.bind(null, 1, 2), clikHandler2, ...) }}),
]);
```

**Comment by paldepind** [comment]
@yelouafi Doing that requires creating a new function in every creation of the virtual DOM tree. It also requires removing and adding a new event listener function for every event listener for every call to `patch`. In most cases the performance difference probably doesn't matter but especially the later is something that I'd like to avoid.

**Comment by yelouafi** [comment]
@paldepind can't this case be optimized by some delegation mechanism ? Function composition is really powerful and its possibilities are limitless.

**Comment by ericgj** [comment]
@paldepind  I hadn't noticed that the array-style event listeners don't require add an `addEventListener` on each patch thanks to array mutation -- tricky!  (I guess it's OK to assume that you aren't going to independently mess around with the array over in your view).

So presumably with this proposal you could do something like `[compose, f3, f2, f1, always(a)]` to run a value through a pipeline of handlers,  or `[sequence, handler1.bind(null, a), handler2.bind(null, b)]`  to run several handlers in sequence?

**Comment by yelouafi** [comment]
if I understand well the following code from the 'eventlisteners' module

```javascript
if (old === undefined) {
      if (is.array(cur)) {
        elm.addEventListener(name, arrInvoker(cur));
      } else {
        cur = [cur];
        on[name] = cur;
        elm.addEventListener(name, fnInvoker(cur));
      }
    } else if (old.length === 2) {
      old[0] = cur[0]; // Deliberately modify old array since it's
      old[1] = cur[1]; // captured in closure created with `arrInvoker`
      on[name]  = old;
    } else {
      old[0] = cur;
      on[name] = old;
    }
```

then a normal callback is wrapped inside an array. Similarly in updates, there is no removeEventListener/addEventListener but only the callback wrapped in the old array (`old[0] = cur`), thus a normal callback is treated like it was an array invocation. Since they are handled the same way, this means they get the same performance cost (beside creation of a new function object  in the case of functions), am i mistaken ?

**Comment by paldepind** [comment]
@ericgj 

> So presumably with this proposal you could do something like [compose, f3, f2, f1, always(a)] to run a value through a pipeline of handlers, or [sequence, handler1.bind(null, a), handler2.bind(null, b)] to run several handlers in sequence?

These examples would call `compose` like `compose(f3, f2, f1, always(a))` and `sequence` like `sequence(sequence, handler1.bind(null, a), handler2.bind(null, b))`.

@yelouafi 

> then a normal callback is wrapped inside an array. Similarly in updates, there is no removeEventListener/addEventListener but only the callback wrapped in the old array (old[0] = cur), thus a normal callback is treated like it was an array invocation. Since they are handled the same way, this means they get the same performance cost (beside creation of a new function object in the case of functions), am i mistaken ?

That is correct. But that is only because plain functions are _not_ updated. In your last example you did this: `h('a', {on: {click: clickHandler.bind(null, 1, 2) }})`. If `1` and `2` instead had been non-static changing variables then it would not have worked because the initially added event listener function would be kept with its original bound values.

If the sequence of functions invoke is static one could `sequence` only once outside of the virtual DOM generation like this:

```js
var handler1And2 = sequence(clickHandler1, clikHandler2)
[... later ...]
h('div', [
  h('a', {on: {click: handler1And2}}),
]);
```

This avoids unnecessary function creation.

**Comment by paldepind** [comment]
@yelouafi Ops. I had totally forgotten that the event listeners module updates plain functions as well without re-adding event listeners. So this statement is absolutely correct:

> Since they are handled the same way, this means they get the same performance cost (beside creation of a new function object in the case of functions), am i mistaken ?

A function creation is what is saved.

**Comment by yelouafi** [comment]
@paldepind Does this mean the use of `handler.bind(...)` or similar is Ok or at least acceptable?

**Comment by paldepind** [comment]
@yelouafi Yes. But I would avoid `Function.prototype.bind` as it is slow. If you don't need to modify the `this` parameter then using a custom function is better.

I'm currently using this helper in a project without auto currying:

```javascript
Function.prototype.$ = function() {
  var fn = this, args = arguments
  return function() {
    var res = [], i;
    for (i = 0; i < args.length; ++i) res[i] = args[i]
    for (i = 0; i < arguments.length; ++i) res[args.length + i] = arguments[i]
    return fn.apply(undefined, res)
  }
}
```

I enjoy it quite a bit.

**Comment by yelouafi** [comment]
@paldepind that's useful to know, although i would prefer using a 'non-method' bind function. 

As i said above, i think snabbdom should focus on more low-level things (like event delegation) and let the already powerful functional tools handles the composition concern.

**Comment by ericgj** [comment]
Great that functions don't force remove/add event listeners either. So the difference between array and function methods is basically whether or not you need access to the underlying DOM event?

@yelouafi  what would event delegation look like here?  You need some kind of top-level table matching event targets to listeners right ? Which suggests some infrastructure would be needed in the core library - it could not simply be done in a module/plugin. I'm not against the idea, just trying to think through the implications. My sense is that automatic event delegation does add some complexity/overhead so if it is added, it should be optional. But I'd like to read more about the performance benefits of it for particular situations.

**Comment by paldepind** [comment]
> that's useful to know, although i would prefer using a 'non-method' bind function.

Sure. I can understand that.

> As i said above, i think snabbdom should focus on more low-level things (like event delegation) and let the already powerful functional tools handles the composition concern.

It is not about composition. It is strictly a feature for customizing which parameters the event listener should be invoked with. And both options are available.

**Comment by yelouafi** [comment]
@ericgj it was just a rapid idea. But yes i think that implementation would need some support in the patch function. For performance, i think in the cases where event listeners aren't added frequently (which is 99% of the case i've seen) performance gains are not obvious.

@paldepind 
yes the composition term was a bit inaccurate. i used it in the sens of something like

```javascript
on: { input: sequence(targetValue, Action.SetText,  someListener) }
```

which i think corresponds to what you said

**Comment by paldepind** [comment]
@yelouafi 

> which i think corresponds to what you said

Yes. Basically is handles invoking functions with a set of parameters so you don't need to do partial application.

This has been implemented so I am closing the issue.
