### ISSUE TITLE
Only update and insert works

### ISSUE THREAD

**Issue by partially-applied** [paldepind/snabbdom#130]
I think the only hooks that work ( have not tried destroy,remove)

is update and insert

```livescript
v-dom = h 'div','hello world'



hook = {}

hook.post = !->
	console.log 'post'
hook.update = !->
	console.log 'update'

v-dom.data.hook = hook


new-v-dom = patch (document.getElementById 'app'),v-dom




<- wait 500

v-dom1 = h 'div','hello world1'


hook = {}

hook.post = !->
	console.log 'post1'
hook.update = !->
	console.log 'update1'

v-dom1.data.hook = hook


new-v-dom1 = patch v-dom,v-dom1
```

**Comment by partially-applied** [comment]
Okay, so looking at the source. It looks like `postpatch` works. 

```livescript
hook.postpatch = !->
	console.log 'post'
```

**Comment by TylorS** [comment]
Check out the documentation underneath the table. It says whats available as a module hook and as a vnode hook. https://github.com/paldepind/snabbdom#hooks

**Comment by partially-applied** [comment]
Hmm. I came across that but did not quite understand the difference. 

Why do modules get different hooks then individual dom elements ?

**Comment by TylorS** [comment]
https://github.com/paldepind/snabbdom/issues/25
https://github.com/paldepind/snabbdom/issues/37
https://github.com/paldepind/snabbdom/issues/55#issuecomment-175161271

Basically hooks have been added as needed with proven use cases

**Comment by partially-applied** [comment]
Oh right. 

I might distill down the use case for each since its confusing.

cheers tylor !
