### ISSUE TITLE
Release a new version with TypeScript type definitions

### ISSUE THREAD

**Issue by staltz** [paldepind/snabbdom#136]
![please](https://cloud.githubusercontent.com/assets/90512/17033583/85f2f60e-4f87-11e6-8399-0476481671e8.jpg)

**Comment by paldepind** [comment]
Thank you for the cute cat.

There you go :smile:

**Comment by tinchoz49** [comment]
haha that's the way to ask things :smile_cat:

**Comment by staltz** [comment]
Thank you.
