### ISSUE TITLE
There is no way to patch element with id and classes without replacing it

### ISSUE THREAD

**Issue by grimalschi** [paldepind/snabbdom#138]
There is no way to patch already existing element with classes and id, if root vnode also has id or classes.

```
var elm = document.createElement('div');
elm.setAttribute('id', 'testid');

var vnode = h('div#testid', 'testtext');
patch(elm, vnode);

console.log(elm === vnode.elm); // false
console.log(elm.innerText); // ''
console.log(vnode.elm.innerText); // 'testtext'
```

**Comment by grimalschi** [comment]
Sorry, I found the way.

```
var elm = document.createElement('div');
elm.setAttribute('id', 'testid');

var vnode = h('div', 'testtext');
patch(elm, vnode);

console.log(elm === vnode.elm); // true
console.log(elm.innerText); // 'testtext'
console.log(vnode.elm.innerText); // 'testtext'
```

**Comment by grimalschi** [comment]
So if root vnode has any id or classes, real node will be replaced with new dom element.

This is the intended behavior, or is it worth to fix?

**Comment by TylorS** [comment]
It is intended behavior. If you need to dynamically change an id or classname I'd use the `prop` and `class` module respectively.

```js
h('div', {
  props: { id: 'somethingUnique' },
  class: { class1: true, class2: false }
}, 'testtext')
```

**Comment by grimalschi** [comment]
Ok, thank you!

**Comment by paldepind** [comment]
Yes. The classes and id's inside the selector are static. This has advantage that Snabbdom can use this static information exactly to determine if an element should be replaced. This makes using `key` unnecessary in many cases.
