### ISSUE TITLE
SVG Support in IE 

### ISSUE THREAD

**Issue by sk1981** [paldepind/snabbdom#140]
The SVG support will not work in any IE (including IE 11) as IE does not supports classlist on SVG elements. Few other browsers like UC browser also have the same issue.

The workaround I used was to set the classes using "attrs".

While I don't think we need to fix it as there is a workaround, it may make sense to add this information in the SVG section.

Thoughts ? Happy to make submit a pull request if it sounds good.

**Comment by paldepind** [comment]
Thank you for reporting this. SVG does work as long as you don't use the classes module? Is that correctly understood?

I think having this in the documentation would be a great idea.

**Comment by sk1981** [comment]
Yes, that's right, classes modules does not works in these cases.

Will create a PR to add the details to the SVG section.

**Comment by sk1981** [comment]
Created a PR for this : https://github.com/paldepind/snabbdom/pull/144

One more thing I did not mentioned above, but had tried was setting the class directly on the element like using h('circle.my-circle'). This fails for most browsers in strict mode due to the fact that ***className*** property for SVG elements is a read-only property and we use ***elm.className*** for attaching classes while creating the elements. 

We can fix this by using elem.className.baseVal or elem.setAttribute to fix this. 

Let me know what you think.

**Comment by sk1981** [comment]
closing this, will create separate one for SVG.className issue later.
