### ISSUE TITLE
Missing hook between prepatch and update

### ISSUE THREAD

**Issue by axefrog** [paldepind/snabbdom#147]
I'm currently implementing a generic virtualised scrolling solution via a Snabbdom module, and this requires background removal and restoration of DOM elements based on scroll position. Snabbdom expects elements to be where it put them in order to do its job properly, so it's important that I am able to remove elements after it does its work, and restore them before it starts making assumptions about their existence in the DOM. Almost all of the available hooks are perfectly fine for this, but there is one omission that makes this difficult without duplicating the work that the prepatch stage is doing.

https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L196-L202

Line 191 triggers the prepatch hook, and this occurs before it is known whether or not the node will be removed, replaced or patched. In other words, it is triggered for all elements, which means restoring previously-removed elements from a virtual cache is not feasible, as it would defeat the purpose of the virtualised scrolling to begin with.

Line 204 triggers the update hook, which is the very next available hook after prepatch.

*Between prepatch and update*, line 197 can run if the node is going to be replaced, and it makes the (usually reasonable) assumption that the DOM is as Snabbdom left it, and can be traversed accordingly. Unfortunately, I need the ability to insert the expected element back into the DOM before Snabbdom starts making decisions based on its presence, and there is currently no hook to do that.

My current workaround will be to duplicate the code on lines 195 and 196 in my prepatch hook, but it makes sense to me that, for Snabbdom to give maximum power to modules to expose unique and interesting functionality, a hook should exist that indicates that a node is about to be replaced, and that it should fire *before* any DOM read operations are performed. I could then insert the element-to-be-replaced back into the DOM before Snabbdom attempts to read the element's parent node so that the new element can be inserted in place.

I'd suggest "replace" for the hook name, in the same vein as "update" firing before the update actually occurs.

**Comment by paldepind** [comment]
Thank you for opening this issue.

> it makes sense to me that, for Snabbdom to give maximum power to modules to expose unique and interesting functionality, a hook should exist that indicates that a node is about to be replaced, and that it should fire before any DOM read operations are performed. 

Yes, I agree. If a hook is useful for some purpose then it should exist.

To be honest what is surprising me the most right now is that the lines [196-202](https://github.com/paldepind/snabbdom/blob/1bfb2834db6fc030aaf6505bacfa97cdc5fabee6/snabbdom.js#L196-L202) exists. I don't think `patchVnode` should ever be called with two vnodes that are not identical. In fact, all invocations of `patchVnode` except the one at line [174](https://github.com/paldepind/snabbdom/blob/1bfb2834db6fc030aaf6505bacfa97cdc5fabee6/snabbdom.js#L174) are directly preceded by a check that ensures that `sameVnode(oldVnode, vnode)` is `true`.

The lines 196-202 are never being being hit by the tests. But I think they might be triggered if two sibling nodes have the same `key` property, but not the same selector (i.e. tags). That's not really intended usage but I guess in that case it would be better to just do a remove and an insert. Then the check inside `patchVnode` could be removed.

What do you think?

**Comment by axefrog** [comment]
Sorry for the slow reply. I ended up taking a different approach to what I was working on, and this ceased to be an issue for me. I was trying to do things with Snabbdom that it's not really designed to do, so perhaps this issue isn't worth pursuing?

**Comment by paldepind** [comment]
@axefrog Ok :smile: I'm quite curious about what you where doing so that L196-L202 where being run? As I mentioned, to me it looks like those shouldn't even be there.

**Comment by axefrog** [comment]
Sorry for the large delay in reply! What I was trying to do was implement a virtualised scrolling solution where I could have tens or hundreds of thousands of elements in a list, but with only a subset of those being rendered in the container at a time. As you scroll up or down, the rendered subset would change depending on scroll position. I changed my approach to manage the subset in advance of Snabbdom, with Snabbdom's thunks and fast patching taking care of the rest of the performance story.
