### ISSUE TITLE
Rendering webcomponents on the server side

### ISSUE THREAD

**Issue by tusharmath** [paldepind/snabbdom#153]
Is there a way to render web-components on the server side?

**Comment by acstll** [comment]
Yes, you can use the [`snabbdom-to-html`](https://github.com/acstll/snabbdom-to-html) module.

Pass a vnode to the `toHTML` that the module exports and you get an HTML string you can use to generate a server response. (You need some extra markup, `<html><body>...` etc. to insert your components into, you have to do that yourself).

**Comment by tusharmath** [comment]
@acstll That won't work for webcomponents. For instance if I have a custom input box such as —
```js
h('x-custom-input-box')
```
The inner HTML would remain unknown to both the browser as well as the server. In the browser we can you `document.registerElement('x-custom-input-box', {prototype})` but I feel it would have been great if something like this was available to snabbdom as well.

I think this can be done via some external plugin and needn't be a part of snabbdom.

**Comment by acstll** [comment]
@tusharmath you're right, I missed that one, sorry!
