### ISSUE TITLE
Using shadowRoot as the root node throws an exception

### ISSUE THREAD

**Issue by tusharmath** [paldepind/snabbdom#158]
**Code**
on creating [custom elements] —
[custom elements]: html5rocks.com/en/tutorials/webcomponents/customelements/
```js

createdCallback() {
  const root = this.shadowRoot()
  patch(root, h('div', ['Hello World']))
}

```

**Actual Behaviour:**
```error
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
```
Line: https://github.com/paldepind/snabbdom/blob/5b2d0de463d0de68db5b62c579031905131fe29e/snabbdom.js#L42

**Expected Behavior**
No exception

**Comment by paldepind** [comment]
Hello @tusharmath. Thank you for reporting this issue :smile:

You mentioned that #159 might fix the issue for you. Did it change anything?

**Comment by tusharmath** [comment]
@paldepind Nope :( This issue happens because `tagName` isn't available on shadowRoot components. We could use `nodeName` in that case.

The second issue is snabbdom looks for the parent node and tries to insert the new node into it. Again with the shadowRoot there is no parent. 

The solution that I have adopted is to create a dummy node inside the shadow root and send that to snabbdom for patching, this solves the above two issues. I think im fine by it and will so be closing this issue.
