### ISSUE TITLE
Speed vs low memory usage. Which strategy?

### ISSUE THREAD

**Issue by ismail-codar** [paldepind/snabbdom#19]
Vnode's elm property provides quick access to the dom elment when patching that's true. But likely to hold up too much space in the memory. This will be problem in big tree structure on the low-profile mobile like devices.

Could elm property reference string is used as Id instead of direct dom object . Are we lost a lot of speed?

For Example:
```javascript
//hyperscript
h("button", "Button")
//and generated vnode structure may be like
{
	sel: "button"
	text: "Button"
	elm: "autoGeneratedId"
}
```
 can be rendering 
```html
<div snabbdom-id="autoGeneratedId">Button</button>
```
To access the actual dom object if desired in patch process we can be use as 
```javascript
var elm = document.querySelector("[snabbdom-id='autoGeneratedId']")
.......
```
https://github.com/matt-esch/virtual-dom#example uses another strategy. Anything about  on the vnode tree for dom referencing. In outside dom object created with the createElement function is used in the patch process. But I can patch each vnode in snabbdom because each node contains elm property. I love it.

Another google project https://github.com/google/incremental-dom they are using very different methods to provide low memory usage.

**Comment by ooflorent** [comment]
It is not a problem to reference the DOM node since it is a reference (not a copy). Moreover the DOM node is created because it is inserted into the DOM tree! 

Other virtual DOM libraries decouple the DOM and the VDOM to enable server-rendering, not to optimize memory.

**Comment by paldepind** [comment]
Yes. @ooflorent is right.

I was going to say the same thing but somehow forgot about this question. Sorry about that.
