### ISSUE TITLE
style module does not remove old styles

### ISSUE THREAD

**Issue by ericgj** [paldepind/snabbdom#21]
If you remove a style from the vnode between patches, the style is not removed from the underlying element. It only adds and updates styles. Don't know how common this would be in practice, but I just got bitten by it today. I could open a PR if you agree it's a bug.

**Comment by paldepind** [comment]
Yes. You're right. I think that is a bug.

It has never bothered me though. So I'm curious,  how did you get bit?

**Comment by ericgj** [comment]
Toggling `display: none` , which in retrospect is usually unnecessary in virtual DOM views, and simple opacity transitions work nicely.  (Speaking of which there are a few typos in the README transitions examples which I will send a PR on too).

**Comment by gaydenko** [comment]
@ericgj , have you tried `display: ''` ?

**Comment by paldepind** [comment]
I've updated the documentation on the style module. What do you think @ericgj?

**Comment by ericgj** [comment]
Looks good. Revert away :+1:
