### ISSUE TITLE
Expose all hooks for modules

### ISSUE THREAD

**Issue by yarray** [paldepind/snabbdom#25]
I'm happy with the library for its simplicity, performance, and extensibility. It became even more exciting when I discovered that I can write modules to extend that. However, currently only ```['create', 'update', 'remove', 'destroy', 'pre', 'post']``` can be used when defined in a module. I'm wondering if it is possible to also expose ```'insert', 'prepatch', 'postpatch'```? For me specifically it will be convenient if I can use ```'postpatch'```, since I want to do some manipulation after all nodes are loaded. 

I saw that a quick solution is to just add the 3 hooks into the ```hooks``` Array before the definition of ```init```. Are there some concerns not to include all hooks here?

Also it seems that a documentation for developing modules is missing. Although it is really easy to write if we read the code, it's better to at least mention that in README so new comers like me won't miss the treasure:)

**Comment by paldepind** [comment]
> For me specifically it will be convenient if I can use 'postpatch', since I want to do some manipulation after all nodes are loaded. 

`postpatch` is invoked every time a node has been patched against an older instance of itself. Is that what you're interested in? And are you interested in hooking into that for _all_ nodes? If you are I'd be willing to add global hooks for both `insert`, `prepatch` and `postpatch`. It's just I've never had the need for using these on all nodes. And then adding them selectively inside `create` handlers will be more performant. But you mention that solution yourself.

> Also it seems that a documentation for developing modules is missing. Although it is really easy to write if we read the code, it's better to at least mention that in README so new comers like me won't miss the treasure:)

I very much agree. It's just something I haven't got around to do. But having people asking for it is always motivating :)

**Comment by yarray** [comment]
Thanks for your reply. The situation is that I want to integrate an external library with snabbdom, which needs to manipulate nodes based on their status. To be more specific, I would like to use the Masonry library:

http://masonry.desandro.com/layout.html

with the most trivial layout:

``` javascript
h('ul', [h('li'), ...])
```

I had to call ``layout`` in a hook of ``ul``, when some ``li`` are added. Hooking to ``create`` didn't work since it's ``li`` not ``ul`` to be created, also ``update`` didn't work since the new ``li`` had not been rendered so the ``layout`` function cannot see it.

If I understand correctly, this should be added to ``postpatch``.  I'm not very certain about "*all* nodes". Did you mean that it's the same as "update", where it is the module creator's responsibility to filter the data?

**Comment by yarray** [comment]
I find that I also need to use ```imagesloaded``` hook, which makes ```create``` and ```update``` are sufficient now... However I still think it may be meaningful to make global the remaining 3 hooks.

**Comment by paldepind** [comment]
> I'm not very certain about "all nodes". Did you mean that it's the same as "update", where it is the module creator's responsibility to filter the data?

Yes. Exactly. So if you're only interested in the `postpatch` event on certain `ul` elements it would be more efficient to add a hook directly to the `ul`s.

> If I understand correctly, this should be added to postpatch. I'm not very certain about "all nodes".

That sounds right.

> However I still think it may be meaningful to make global the remaining 3 hooks.

You do have a point. But I think I would prefer to do so given an actual use case. I'm wary about adding features without an actual need.

**Comment by yarray** [comment]
> Yes. Exactly. So if you're only interested in the ```postpatch``` event on certain ```ul``` elements it would be more efficient to add a hook directly to the ```ul```s.

My idea is to create some "behaviors" so it can be reused and enable better separation of concern. But it may be more about taste. An assumed example is:

``` javascript

// a normal span
function view() {
    return h('span', 'foobar');
}

// an animated version
function view2() {
    return h('span', { xxxAnimated: { duration: 1 } }, 'foobar');
}
```

> You do have a point. But I think I would prefer to do so given an actual use case. I'm wary about adding features without an actual need.

That's quite reasonable. I will tell if I have some actual needs later. Thank you again for your instructions. I'm closing the issue.
