### ISSUE TITLE
Link to the Functional Architecture examples

### ISSUE THREAD

**Issue by xuoe** [paldepind/snabbdom#26]
I'm really liking what you're building here, @paldepind, and I was thinking it'd be a good idea to include a link to [the functional architecture examples](https://github.com/paldepind/functional-frontend-architecture) somewhere in the README, as that helped me quite a bit getting started with all this.

Additionally, including a link to the actual source code for the two current examples might also be helpful.

I can create a PR with the necessary changes, if you'd like. Thanks!

**Comment by paldepind** [comment]
Snabbdom is meant to be a low level virtual DOM library. It can certainly be used together with the functional architecture but it can also be used to build other architectures.

I think having a link to [functional frontend architecture](https://github.com/paldepind/functional-frontend-architecture) is a good idea. But it must not sound like that is the only way to use Snabbdom.

Links to the examples source code is also a good idea!

**Comment by paldepind** [comment]
[The readme](https://github.com/paldepind/snabbdom#structuring-applications) now links to the functional frontend architecture repository as well as to @TylorS's Motorcycle.js.
