### ISSUE TITLE
Real DOM widgets in snabbdom

### ISSUE THREAD

**Issue by mpal9000** [paldepind/snabbdom#28]
Hi, what is the equivalent of a `virtual-dom` `widget` in snabbdom?

**Comment by paldepind** [comment]
Widgets in virtual-dom is just a way to hook into the patch process. IMO it is an overly complex way to do it. Snabbdom gives you both the [equivalent and additional hooks](https://github.com/paldepind/snabbdom#hooks) both on a per node and globally (i.e. on all nodes).

**Comment by mpal9000** [comment]
Yeah, the many hooks are definitely one of the strengths of snabbdom. Thanks!

**Comment by r24y** [comment]
So just to make sure I understand, `vnode` refers to an actual DOM node? I'm trying to get a reference to an actual DOM node so I can instantiate a three.js scene inside of it.
