### ISSUE TITLE
virtual-dom thunk equivalent?

### ISSUE THREAD

**Issue by zywind** [paldepind/snabbdom#29]
This is an exciting project. I wonder if you have plans to implement virtual-dom thunk like structures, so that some parts of the vdom don't have to be diffed if their states haven't changed.

Also, you might want to look at cyclejs, which is an architecture combining FRP with virtual dom.

**Comment by tinchoz49** [comment]
hi! @zywind i agree with you, this a great project! <b>flyd</b> too ;)!

About the thunk implementation: [thunk](https://github.com/paldepind/snabbdom/blob/master/thunk.js)

Maybe It would be good to have an example of thunks in action. I don't know if there is something like that.

**Comment by paldepind** [comment]
I'm happy to hear you think so.

As pointed out by @tinchoz49 Snabbdom already has thunks. Unfortunately there isn't a proper example. Only the [tests](https://github.com/paldepind/snabbdom/blob/master/test/thunk.js).

**Comment by paldepind** [comment]
I've hastly written a [description of thunks in the readme](https://github.com/paldepind/snabbdom#thunks).

I'm certain it could be better. What is still unclear?

**Comment by tinchoz49** [comment]
nice!! thanks @paldepind !

**Comment by zywind** [comment]
Thanks @paldepind for being so responsive. The description is pretty good. There are just a few typos. You had "thunks" in the first few paragraphs instead of "thunk".
