### ISSUE TITLE
HTML output support

### ISSUE THREAD

**Issue by TylorS** [paldepind/snabbdom#30]
I'm currently working on an integration of snabbdom with Cycle.js, but to be at feature parity with the current Cycle.js solution for view rendering I would need a way to output HTML on the server-side. Are there any solutions that I'm not currently able to find or is this on the roadmap of things?

Thank you for your time and for your work on this library!

**Comment by ismail-codar** [comment]
You can use jsdom easily. I have tested this but style module requires reuetAnimationFrame polyfill for jsdom.

```javascript
var snabbdom = require('snabbdom');
var patch = snabbdom.init([ 
  require('snabbdom/modules/class'), 
  require('snabbdom/modules/props'),
]);
var h = require('snabbdom/h');

require("jsdom").env('<html><body></body></html>', function (err, window) {
	global.Element = window.Element;
	global.document = window.document;
	var vnode = patch(document.body, h("button", ["Test button."]));
	console.log(vnode.elm.outerHTML);
	window.close();
});
```

**Comment by TylorS** [comment]
Thank you for your response. How is the performance of this? I'm totally unfamiliar with jsdom.

**Comment by ismail-codar** [comment]
Some humans says jsdom full featured but slow. In our scenario, most of the unnecessary features. Loading external resources, cookies etc are  unnecessary for snabbdom. 
Lightweight jsdom alternatives may be usefull. 
If you search and test can you share results with us?

**Comment by TylorS** [comment]
Absolutely! I like the idea of using something like jsdom, as I don't have to write yet another library to maintain. I'll likely investigate a slimmer alternative in the coming days. I'll keep you posted.

**Comment by paldepind** [comment]
> I'm currently working on an integration of snabbdom with Cycle.js

That is a great idea and very interesting!

There currently isn't a Snabbdom specific way to convert virtual nodes to HTML strings. Implementing such a thing is not particularly hard. I've looked at other vdom libraries approach and it's quite simple. The only challenge is that because Snabbdom is extendable with modules the HTML output would have to be extendable as well.

**Comment by TylorS** [comment]
If you're interested I have a working version here at https://github.com/TylorS/cycle-snabbdom. Bare in mind it's a WIP

**Comment by TylorS** [comment]
I was wondering if anyone has attempted to start this yet? I was going to, if no one else has. If not, I'm also curious as to whether that work should be in this repo or in another `snabbdom-to-html` or something like that?

**Comment by acstll** [comment]
@TylorS 

I was trying the same thing a few days ago. I was planning or proposing a `snabbdom-server` module, with a single method (for now). It would be something like this:

```js
require('html-element')

function renderToString (patch, source) {
  var target = document.createElement('div')
  patch(target, source)
  return target.outerHTML
}

exports default { renderToString }
```
where `source` is a vnode from snabbdom (anything you get out of the `h` function), and `patch` is the one you know from snabbdom :smile: 

It works because by simply requiring the [`html-element`](https://www.npmjs.com/package/html-element) package, all (well, not all) the DOM related functions are available on the server.

In order to make this work completely, a PR for `html-element` would be needed, to implement the `nextSibling` method (and any other used in snabbdom not yet implemented). It shouldn't be hard. I just hadn't had time to do it.

It'd be also interesting to know if @paldepind thinks including such a thing as a helper would be cool, or if an external module would be better…

**Comment by acstll** [comment]
I just actually tested this in `node` and it's not that straight-forward, `html-element` would need more tweaking than I first thought.

```
/Users/A13/dev/snabbdom-server/node_modules/snabbdom/snabbdom.js:217
        oldVnode.parentElement.replaceChild(vnode.elm, oldVnode);
TypeError: Cannot read property 'replaceChild' of undefined
```

There's also `requestAnimationFrame` being used globally on the `styles` module.

Any ideas? Can this be a thing?

**Comment by TylorS** [comment]
That's very interesting @acstll. I was looking at removing the need for `patch()` altogether. Taking the object representations of the DOM 

```
{
  sel: "div",
  data: {...},
  text: undefined,
  children: [...],
  elm: undefined, // ignored?
  key: undefined // ignored?
}
```

And creating HTML strings directly from there.

**Comment by TylorS** [comment]
I have a working version started here at: https://github.com/TylorS/snabbdom-to-html

I'm sure there are at least a couple of edge cases I need to consider, as well as maybe many places to refactor and adjust for performance.

**Comment by TylorS** [comment]
Also, it's not extensible like Snabbdom is, it only takes ouputs things from the props, style, and classes modules currently. I'd like to handle this in a modular similar to how Snabbdom itself does it in the future. It currently ignores the attrs and event-listeners modules, as it doesn't fit my use case just yet.

This is only a rough draft I whipped up in about 2 hours, but I'd love any help polishing it up.

**Comment by acstll** [comment]
@TylorS inspired by your comment and your code, I reimplemented your idea following a modular approach just like in snabbdom (I felt bad about making yet another module, I was trying some ideas and ended up half-way there!).

https://github.com/acstll/snabbdom-server

Is this what you were talking about when you said "modular"?

It's not on npm since **it's not finished** and I'd like to hear opinions!

**Comment by TylorS** [comment]
@acstll Yes, much closer to what I had envisioned, but lacked time to actually do. That looks quite great! Especially next to mine :wink:. 

I'm curious to what you think is unfinished as of right now? I'll definitely help out and submit some PR's as HTML output is very important for the framework I'm building currently.

**Comment by acstll** [comment]
@TylorS cool, I'm glad it works for you!

I consider it finished right now. There's only 2 modules as you can see, one handles styles and the other attributes and classes (I merged both into one to be able to handle the 3 possible class inputs nicely, which are the `class` object, `attrs.className` and the selector. The `class` object takes precedence and then it dedupes with anything present in the selector.)

Of course, feel free to test it with your framework and submit PR's. Check out the tests if you can as well, I tried covering as much as I could think of. I'd like the module to be as much spec-ish as possible regarding HTML.

I'll make it ready for npm later today.

**Comment by TylorS** [comment]
@acstll 
Might I suggest a different name though? I'd be glad to give you `snabbdom-to-htm`l if you'd like that. I feel as `snabbdom-server` is a bit misleading, and doesn't quite give away it's intent.

**Comment by acstll** [comment]
@TylorS that's no problem. I actually like snabbdom-server but ..to-html is exactly what it does. :smile:  I'll change it to `snabbdom-to-html` then in the repo, you can add my user in `npm` so I can publish it. Is that ok?

**Comment by TylorS** [comment]
That's sounds good, I've never done it before, so give me a minute. I'll report back.

**Comment by TylorS** [comment]
Done!

**Comment by acstll** [comment]
That was quick. I'll make it ready and publish it in the next couple of minutes then. Thanks!

**Comment by TylorS** [comment]
Thank you :+1:

**Comment by acstll** [comment]
No problem, let me know how it goes.

**Comment by TylorS** [comment]
Will do, I'll open any issues I come across on your repo. Thanks for the great work!

**Comment by TylorS** [comment]
@acstll I started working on my own library which uses your library and I can report no issues so far!

**Comment by acstll** [comment]
@TylorS brilliant! I've seen it https://github.com/motorcyclejs/html :smile: 

I have an idea for simplifying the `snabbdom-to-html` API (I'll post an issue on its repo). I also thought we should somehow support `thunks`. Are you using them in your framework?

**Comment by TylorS** [comment]
@acstll Yeah you found where I'm using it.

I'm not currently using any thunks inside of the framework, but It would be expected to  be able to use them while using the framework. It'd be good to have support for them in HTML

**Comment by TylorS** [comment]
I think it's safe to close this? Unless there are any objections?

**Comment by paldepind** [comment]
I think @acstll did a great job on snabbdom-to-html :+1: The modular approach is similar to what I had in mind for server site rendering.

I've added a mention of snabbdom-to-html in the readme.

**Comment by artfuldev** [comment]
How do I turn off html-encoding in snabbdom-to-html used in cyclejs?
