### ISSUE TITLE
Snabbdom patches over given container

### ISSUE THREAD

**Issue by TylorS** [paldepind/snabbdom#31]
While I've been writing my intergration for snabbdom with Cycle.js, I've come to notice  that running for example `patch(document.querySelector('.app'), view)`, snabbdom is actually patching *over* `.app`. However my needs are for the view to be appended to `.app`, because I need to listen to events relative to `.app`. Is there a way to do this currently or is it possible to add support for this? I'd be happy to submit a PR if it is needed and would be accepted.

Thank you for your time.

**Comment by TylorS** [comment]
Also just found out that if I run patch over `document.querySelector('body')` it even overwrites `body`. Surely this must be unwanted behavior?

**Comment by ismail-codar** [comment]
This is @paldepind 's strategy. https://github.com/paldepind/snabbdom/issues/9

**Comment by TylorS** [comment]
This feels very unintuitive coming from Virtual-DOM, but thank you for your answer.

**Comment by TylorS** [comment]
This feels very unintuitive coming from Virtual-DOM, but thank you for your answer.

**Comment by paldepind** [comment]
I'd like to hear why you prefer the other behaviour? I like to do stuff like this

```js
patch(document.body, h('body', /* something something vnode */ );
```

**Comment by TylorS** [comment]
Currently, maybe just for my use case, there is no way for me to know if
the element I'm patching doesn't have other CSS classes or an id or any
other properties that they may use inside of there application. Sure I
could check but this would come at a performance loss. We're all trying to
avoid working with the DOM directly.

I guess really my biggest gripe is that coming from using Matt Esch's
virtual-dom library this is how it works, and its also how it works with
Google's Incremental-DOM library. Maybe I'm wrong, but as someone who
hasn't tried snabbdom before I would expect this to be the default
behavior.

I'm also investigating the use of snabbdom primarily for potential
performance gains compared to the previous libraries I mentioned (also very
excited about the modularity) and having to workaround the default behavior
would likely come at a performance loss.

**Comment by Frikki** [comment]
I don’t think that replacing the root selector is a good design decision.

- virtual-dom is widely used and a transition to Snabbdom is not fluent.
- it is a surprising and unexpected side-effect.
- it potentially (read: most likely) breaks layouts

Example:
```html
<div class="app is-loading">
  <p>...loading</p>
  <p>This will only take a moment...</p>
</div>
```

**Comment by Frikki** [comment]
> @paldepind I don't think that's necessarily an issue.

Perhaps not necessarily, but in many use cases it is. For example, when *Snabbdom* should be used by other libraries or frameworks with a present API that are massively consumed by their end-users, which hide the DOM rendering implementation, then all end-users would be required to rewrite their initial DOM. As in the example given above, if the end-user would call an API like `startApp(`.app`)`, which is not uncommon, the library or framework would, if no behavior should break, be required to inspect the selector element for *id* and *complete range of class names*. While this may not from a naive point of view seem like a great deal, it does have performance impact. Even in the most simple replacement of, e.g., *virtual-dom* with *Snabbdom*, it still requires the user to change his code.

My position is that it would be a better approach to make such a replacement/swap as friction free as possible, i.e., adhering to the established behavior of hyperscript, as implemented by several other virtual dom libraries.

**Comment by TylorS** [comment]
@paldepind Thank you for being open to this change, it is truly appreciated. 

To be honest, I currently do not know how the aforementioned libraries, and likely others, accomplish this behavior. 

I was wondering if this is something you are currently working on? I'd be willing to investigate how it's done in virtual-dom and take a swing at a PR if you're not already working on this.

**Comment by paldepind** [comment]
> I think @Frikki's comments also give good reason for the change.

To me the primary argument is that this is what virtual-dom does. Since changing it doesn't compromise on any of the goals of Snabbdom I see no reason to do it differently. But I don't think virtual-dom's way is necessarily better for Snabbdom. There is a certain consistency in always patching from the root of the first argument given to `patch`.

And of course Snabbdom will never be completely compatible with virtual-dom. It does some things quite differently in order to achieve it's better performance, smaller code base, extra hooks and improved modularity.

> I was wondering if this is something you are currently working on? I'd be willing to investigate how it's done in virtual-dom and take a swing at a PR if you're not already working on this.

Thank you a lot for your offer! But I've actually just taken a stab at this myself. I'd highly appreciate if you would try out the branch [patch-under-container](https://github.com/paldepind/snabbdom/tree/patch-under-container) and see if it works for you.

With the, quite small actually, changes in the branch if your HTML looks like this:

```html
<div id='container'>Blah blah</div>
```

And you do `patch(container, h('div', 'Hello there'))` then the HTML will end up like this:

```html
<div id='container'>
  Blah blah
  <div>Hello there</div>
</div>
```

If there's something I've misunderstood and/or if it doesn't do the right thing please let me know :)

**Comment by Frikki** [comment]
@paldepind I agree that *virtual-dom*’s way isn’t *necessarily* better. When I first started using *virtual-dom*, I actually was surprised by the way it worked, and I expected it to actually work the *Snabbdom* way. However, I don’t think you have addressed the case mentioned under *Update* in my previous comment. Regardless, many thanks for addressing our concerns with your branch update. I’ll test it and report my findings back to you. Cheers.

**Comment by avesus** [comment]
Which useful things could _incremetal_ `patch()` function call do??? I completely don't understand the purpose of NOT OVERRIDING of ALL contained before DOM. In such way you definitely store your state in DOM. Call to patch definitely HAVE to be idempotent to behave like in React, or it is useless.

**Comment by paldepind** [comment]
> I agree that virtual-dom’s way isn’t necessarily better. When I first started using virtual-dom, I was actually surprised by the way it worked, and I expected it to work the Snabbdom way.

Then it sounds like we agree :smile: 

> However, I don’t think you have addressed the case mentioned under Update in my previous comment.

That is true. Sorry about that. I don't understand the problem you're describing though. I don't think manually adding classes is a problem.

**Comment by paldepind** [comment]
> Which useful things could _incremetal_ `patch()` function call do??? I completely don't understand the purpose of NOT OVERRIDING of ALL contained before DOM. In such way you definitely store your state in DOM. Call to patch definitely HAVE to be idempotent to behave like in React, or it is useless.

I don't understand. `patch` is idempotent both now after after this potential change.

**Comment by Frikki** [comment]
@paldepind Example:

```html
<div class="app">
  ...
</div>
```

```js
patch(document.querySelector(`.app`), aViewThatTakesTimeToMake());
```

Say, `aViewThatTakesTimeToMake()` internally depends on some time-taking server requests, but meanwhile another code does something this:

```js
const appElement = document.querySelector(`.app`);
appElement.className += ` an-important-class`;
```

In the current way *Snabbdom* works, wouldn’t `an-important-class` be lost when the actual patching occurs?

**Comment by avesus** [comment]
@paldepind I mean that I disagree that it is ok 
```html
<div id='container'>Blah blah</div>
```
And you do patch(container, h('div', 'Hello there')) then the HTML will end up like this:
```html
<div id='container'>
  Blah blah
  <div>Hello there</div>
</div>
```
patch(container, h('div', 'Hello there')) IMO should remove 'Blah blah'.

**Comment by Frikki** [comment]
@avesus But that is not the behavior we are discussing to implement.

**Comment by Frikki** [comment]
@paldepind But I actually *do* think that the current behavior is a better approach. My main concern is people migrating from *virtual-dom*. But perhaps this shouldn’t even work as an argument, because *virtual-dom*’s implementation may be the poorer choice.

**Comment by paldepind** [comment]
@Frikki 
Regarding your example. What does `aViewThatTakesTimeToMake` return? If you pass its return value to `patch` it must return a virtual node. Thus it must be a synchronous function. Then it's not possible to change things in between the invocation to `aViewThatTakesTimeToMake` and `patch`?

But, generally if you manually modify the DOM and then later patch it with a virtual DOM library then things _might_ conflict. Not necessarily though. If you manually add a class and nothing in your virtual dom mentions that class then Snabbdom will not touch it.

@avesus 
So you prefer the current behaviour?

> Otherwise, it is possible to store state in DOM. Could Snabbdom be configured to not respect such sort of support of jQuery integration etc.?

Can you elaborate on that concern? It's hard to make it completely impossible to store state in the DOM. For instance you could manually add data attributes to DOM elements. Snabbdom will not see them nor remove them. Doing so would have a big performance impact. But as long as you just avoid doing it I don't see the problem?

It's interesting to see how the tides seems to be turning in favour of the current approach :open_mouth:

I don't understand the details of the issues you (@TylorS and @Frikki) are facing with regards to combining Snabbdom with Cycle. But you might be able to achieve more backwards compatibility by doing the initial patch like this:

```js
// `root` is the root element, `vnode` is the initial vnode
var dummyElement = document.createElement('div');
root.appendChild(dummyElement);
patch(dummyElement, vnode);
```

Then `patch` will replace `dummyElement` with the DOM element constructed from `vnode`. This effectively appends to the root element. Alternatively you might require users to construct their virtual dom in a way that is compatible with how Snabbdom currently does it.

I'm still willing to do whatever the majority wants :smile:

**Comment by Frikki** [comment]
@paldepind After having considered the pros and cons of both approaches, I am now favoring the current implementation. Sorry if making a perhaps unnecessary fuzz.

**Comment by TylorS** [comment]
I still disagree. I feel the suggested behavior is better for modularity.
If I have a component it has to know about the container its going to be
patched in, or the container I'm patching to has to know about the
component.

For example, using CSS-modules in my 'main' component it will generate a
hash, something like `main_container_abc12`. There is no way for my html
file to know the CSS class generated. And I think it would be good practice
for my 'main' component to know about `.app` that I'm patching to, it makes
the relationship hardwired.

**Comment by ericgj** [comment]
I don't have a strong opinion either way. I too was confused by patching over at first, coming from virtual-dom, but to me it is a cleaner way. Each node is _either_ under snabbdom's control _or_ under control of some other code - there is no sharing of nodes and unpredictability of updates coming from two places. It seems easy enough to have your "outside" app provide the top-level snabbdom node, and write your CSS against the containing node (which belongs to the outside app, rather than snabbdom.)  But I'm probably missing something in what you are saying @TylorS .  How to integrate CSS-modules with a virtual dom approach is not something I'm familiar with.

**Comment by TylorS** [comment]
What I mean is, when we create a component, whether in Cycle.js or any
other framework, we want them to be reusable. So in a perfect world it
should treat itself as if its the entire universe. If the top-level
component has to mimic the container in which it is going to be patched to,
there is now a codependency. We are unable to freely make changes to one,
without making changes to the other.

I hope that explains my position a bit better.

**Comment by Frikki** [comment]
Now I’m split again. I am all for decoupling, but there are benefits of the *Snabbdom* replacement. I totally get the issues @TylorS is mentioning with, for example, *css-modules*.

**Comment by HighOnDrive** [comment]
Would it not be possible to support both approaches to handling patching? There could be the default way and then an optional param on the patch function if the alternate approach is desired.

**Comment by Frikki** [comment]
Optional parameters with `true`/`false` values provide a poor API. If @paldepind should decide to offer both ways, there should be two distinct functions.

**Comment by paldepind** [comment]
@TylorS

> What I mean is, when we create a component, whether in Cycle.js or any other framework, we want them to be reusable. So in a perfect world it should treat itself as if its the entire universe. If the top-level component has to mimic the container in which it is going to be patched to, there is now a codependency. We are unable to freely make changes to one, without making changes to the other.

The top-level component does not _have_ to mimic the container it is going to be patched to. It will replace the container. If you have HTML like this:

```html
<div id="component">
  <div id="child-1" />
  Something something content.
  <div id="child-2" />
</div>
```

Then you can `patch` child components into `child-1` and `child-2` without knowing anything about them. Whatever they contain will simply replace the "dummy" placeholders. If the view for the first component is `<p>Hello from child</p>` and the view for the second is `<button>Click me</button>` then the HTML will end up looking like this:

```html
<div id="component">
  p>Hello from child</p
  Something something content.
  <button>Click me</button>
</div>
```

There is no codependency. You are free to change both the parent and the child without them affecting each other. Also notice how this approach makes it possible to control exactly where the child components will be inserted. We are not forced to have them appended to the end of some container.

Does the above make sense? Is there some concern that I didn't understand properly?

**Comment by TylorS** [comment]
Yes, you are correct in this case @paldepind. I may be speaking of the approach that is required (maybe simply preferred) in cycle, but maybe other frameworks as well. I'd like to try to elaborate my position, entirely Cycle.js specific.

When creating an application in Cycle.js using what we call a *driver* that interacts with the DOM we will generally have an `index.html` file that looks similar to this:

```html
<html>
  <head>
   <title>Cycle.js Starter</tiltle>
   <link href="styles.css" />
  <head>
  <body>
    <div class="app-container"></div>
    <script src="app.js"></script>
  </body>
</html>
```

The entry point of `app.js` will look something like this:

```javascript
import {run} from '@cycle/core'
import {makeDOMDriver} from 'cycle-snabbdom' // what I'd like to do

function intent({ DOM }) {
  DOM.select(':root').observable.map(root => { // root is where we are patching
    root.classList.contains('.app-container') // => true
  })
  return {
    click$: DOM.select('a').events('click') // listen to click events on '<a>' tags relative (a child of) to '.app-container'
  }
}

function model(actions) {
  ... create state from actions ...
}

function view(state$) {
  return state$.map(state => {
   return h('div', {class: state.isClicked? 'classOne' : 'classTwo'}, [
    ...children
   ])
  })
}

function main(sources) {
  const actions = intent(sources) // actions are what we would like user action to be interpreted as
  const state$ = mode(actions) // state is modeled from the actions for the user
  const view$ = view(state$) // an observable of what the view should look like at any given moment, based on the current state
  return {
    DOM: view$
  }
}

const drivers = {
  DOM: makeDOMDriver(".app-container") // take note of this
}

run(main, drivers)
```

Within the context of Cycle (possibly other frameworks), my `view` function that creates the view should **not**  have anything idea of where it is being patched to. In Cycle, *components*, in most cases, **should** be created as though they are the entire world, unknowing of the outside world. So I should be able to swap the Model/View/Intent (MVI) expressed above with another component that also creates a view, without having to change it.

Which the current behavior, my view would have to return something like 
```js
h('div.app-container'), {}, [...children])
```
In order for the events relative to `.app-container` to continue to work properly.

This is the codependency I'm speaking of. I can't just simply switch my `Main` component out for `otherComponent` without first modifying the view of `otherComponent` to wrap the current view it produces with `h('div.app-container', {}, [...])`

Does this make sense? I'll gladly clarify my position if needed.

**Comment by paldepind** [comment]
As far as I can see in that example the DOM would end up looking like this:

```js
<html>
  <head>
   <title>Cycle.js Starter</title>
   <link href="styles.css" />
  <head>
  <body>
    <div class="classOne">
      ...children
    </div>
    <script src="app.js"></script>
  </body>
</html>
```

The root component becomes a child of body. Why is that undesirable?

Would doing this solve the problem?

```js
// `root` is `.app-container`, `vnode` is the initial vnode returned by `view`
var dummyElement = document.createElement('div');
root.appendChild(dummyElement);
patch(dummyElement, vnode);
```

Does the changes in the mentioned branch solve your issues?

**Comment by TylorS** [comment]
That *is* the DOM that would be represented with the current approach. 

The issue with your 'solution' is that with `makeDOMDriver('.app')`, I now want to listen to events relative to `.app`. It's impractical to listen to event relative to `.classOne` because it could change hundred/thousands of times of the course of my application. If that `<div>` now has the CSS class `classOne` my application is broken. When I realized this is what was happening, that is when I  opened this issue.

I also agree with @avesus that in your example

```html
<div id="container">

</div>
```

**Comment by TylorS** [comment]
Sorry didn't mean to close the issue

**Comment by TylorS** [comment]
Also when switching the component that changes `.app` to `classOne` in the previous example, I may at some point wish to change to a different component that changes `app` to `someOtherClass`, but with the current implementation somehow I have to account for the new root of my application being `someOtherClass`.

**Comment by TylorS** [comment]
Also apologies for not having time to test the branch you mentioned above.

**Comment by paldepind** [comment]
I'm sorry for the late reply here.

> The issue with your 'solution' is that with `makeDOMDriver('.app')`, I now want to listen to events relative to `.app`. It's impractical to listen to events relative to `.classOne` because it could change hundred/thousands of times over the course of my application. If that `<div>` now has the CSS class `classOne` my application is broken because I"m listening to `.app`. When I realized this is what was happening, that is when I opened this issue.

I don't understand this. If I understand you correctly you want to listen to events on the top parent. Wy can't you do that with my solution?

Did you find the time to check out the branch @TylorS?

**Comment by TylorS** [comment]
Hello @paldepind. I actually just did and was writing you a message!

It works just as promised. I recently realized *how* your example would work.
```js
if (oldVnode instanceof Element) {
  ...
}
else {
...
}
```

That code above made it so obvious once I realized what it was doing. My deepest apologies for making claims I didn't fully understand. I was originally under the belief that you always needed reference to an `Element`, which is why I was having trouble understanding.

**Comment by paldepind** [comment]
> My deepest apologies for making claims I didn't fully understand. I was originally under the belief that you always needed reference to an Element, which is why I was having trouble understanding.

Don't worry about it :smile: Does this make the current approach more useful to you or would the code in the branch still be preferable?

Maybe the current documentation isn't good enough at explaining how to use `patch`. Do you have ideas for improvement? I'm thinking about extending the inline example in the readme to also demonstrate a second application of `patch` where the old vnode is supplied.

**Comment by TylorS** [comment]
The current approach is perfectly fine as my current use case requires me to run 
```js
  if ( oldVNode instance Element) {
    oldVNode.innerHTML = '';
  }
```
which would be useless with the proposed behavior.

Regarding the documentation I think it would be good enough to show how the old vnode is supplied. I just never made that connection at first.

**Comment by TylorS** [comment]
I think it's safe to close this, unless there is any opposition?

**Comment by paldepind** [comment]
It doesn't seem like there is :)

**Comment by avesus** [comment]
I'm going mad trying to attach my DOM to SSR-sent HTML DOM rendered by snabbdom-to-html.

The html I send from my server: `<body><div id="root"><div><h1>Hello</h1></div></div></body>`.
Then I call `patch(document.querySelector('#root'), view())` and it adds me another copy (!!!) of the already (!) rendered DOM from my server!

```<body><div id="root"><div><h1>Hello</h1></div></div><div><h1>Hello</h1></div></div></body>```

How to instruct snabbdom to REPLACE that exisitng DOM just by diffing it?

Appreciate any help!

**Comment by paldepind** [comment]
@avesus I think the only thing you can do is manually clearing the body before you call `patch`.

**Comment by avesus** [comment]
That exactly what I do for _workaround_. But it not be default behavior, isn't it? Of course, I don't understand deeply how diffing works. But, really, it is impossible to diff with not earlier patched vnode but with real DOM tree instead? I mean, impossible in principle?

**Comment by paldepind** [comment]
@avesus In principle you can do that. That is what virtual-dom does. But diffing just a real DOM tree against a virtual one is not as fast as diffing two virtual trees against each other. Thus that is what Snabbdom does. In your case it would have been nice if Snabbdom could patch DOM against VDOM. But it would be a lot of extra code. I think the workaround is acceptable. You only have to do it once.

**Comment by avesus** [comment]
@paldepind Thank you Simon! Now I see the point: maybe it even will cost more CPU cycles diffing vdom with real Server-Side Rendered DOM than just to drop the DOM and recreate it from the vdom scratch. By the way, I've invented the same workaround you suggested even before asking the initial question - couldn't think that it is pretty well solution and even not a 'crutch'!

**Comment by leeoniya** [comment]
@paldepind if you split the vtree-build/diff and DOM-hydration stages, it becomes trivial to hydrate the vtree from a server-built DOM without any diffing (assuming from the identical vtree). in domvm, the entire loop is a few lines: https://github.com/leeoniya/domvm/blob/master/src/view.js#L309

**Comment by Izhaki** [comment]
2 years later... just bumped into the same issue.

To begin with, i don't think `container` is the right term - it suggests something that contains (the mounted vdom), whereas in fact it acts more as a `root` or `mount point`.

Anyhow, our use case is this:
- We want to mount SVG elements.
- The SVG tag itself is created externally - we don't want the vdom to create it.
- Reason is separation of concerns. For example, when the screen is resized, we want to update the SVG size and possibly viewport. We don't want this code to live in the vdom part of the app.

**Comment by avesus** [comment]
```js
function nodeListToVnodeList (nodeList) {
  const nodes = [];

  for (let i = 0; i < nodeList.length; ++i) {
    const node = nodeList[i];
    const ve = { elm: node };
    if (node.nodeType === 3) {
      // console.log('text', `\`${ node.nodeValue }\``);
      ve.text = node.nodeValue;
    } else if (node.nodeType === 1) {
      let attrs = {};
      for (let i = 0; i < node.attributes.length; ++i) {
        attrs[node.attributes[i].name] = node.attributes[i].value;
      }
      // console.log(node.localName, attributesMap);
      ve.sel = node.localName;
      ve.data = node.attributes.length ? { attrs } : {};
      if (node.childNodes.length) {
        ve.children = nodeListToVnodeList(node.childNodes);
      }
    }

    nodes.push(ve);
  }

  return nodes;
}

let virtualHtml;

document.addEventListener('DOMContentLoaded', e => {
  virtualHtml = nodeListToVnodeList(document.getElementsByTagName('html'))[0];
  // Initialize
  ...
  // Render the UI state:
  virtualHtml = patch(virtualHtml, veEmptyBody('Hello'));
}, true);

```

**Comment by caramboleyo** [comment]
```javascript
	function emptyNodeAt(elm) {
		// text node
		if (elm.nodeType === 3) {
			return vnode(undefined, undefined, undefined, elm.nodeValue, elm);
		}

		const id = elm.id ? '#' + elm.id : '';
		const classes = elm.getAttribute('class');
		const c = classes ? '.' + classes.split(' ').join('.') : '';

		const data = {};
		const attrs = {};
		for (const att of elm.attributes) {
			if (att.name != 'class') {
				attrs[att.name] = att.value;
			}
		}
		if (elm.attributes.length) {
			data.attrs = attrs;
		}

		const children = [];
		for (const node of elm.childNodes) {
			children.push(emptyNodeAt(node));
		}

		return vnode(api.tagName(elm).toLowerCase() + id + c, data, children, undefined, elm);
	}
```

**Comment by caramboleyo** [comment]
I see there is a tovnode function now:
https://github.com/caramboleyo/snabbdom#tovnode
