### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by ccorcos** [paldepind/snabbdom#33]
Any ideas how to get this to work with React Native? Cause that would be awesome. :+1:

**Comment by paldepind** [comment]
I actually haven't looked at React Native at all. I was under the impression that it was React specific.

Do you think Snabbdom could be made to work with React Native? That would certainly be sweet.

**Comment by ccorcos** [comment]
It is react specific, buy I could imagine two ways of getting it to work.

1) create a shim that renders React elements as opposed to snabbdom elements. I'm thinking somewhere around [here](https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L47) you could just use something like `React.createElement('div', {className:'something'})`. This way, we are using React under the hood and get to benefit from all the millions of dollars Facebook is spending on React.

2) Somehow [hook into the React Native bridge](https://github.com/facebook/react-native/tree/master/Libraries/ReactNative) to talk directly to React Native Obj-C modules over the same async communication layer that React uses. This would be a much larger project though.

**Comment by ismail-codar** [comment]
@ccorcos Looks like only you experienced with react among us. May be tried on modified snabbdom code. Modified createElm function related React.createElement vs document.createElement etc.. If you can do via any way. I think snabbdom may stretch according to this.

**Comment by ccorcos** [comment]
Sounds good -- that would be SWEET!
