### ISSUE TITLE
eventlisteners module problem with shared data

### ISSUE THREAD

**Issue by ericgj** [paldepind/snabbdom#34]
Because this module [mutates the vnode data, replacing a given function with an object pointing to the function](https://github.com/paldepind/snabbdom/blob/master/modules/eventlisteners.js#L26), you can't have multiple vnodes sharing the same data (or to be precise: sharing the same `{on: ...}` branch). 

I don't see an obvious fix for this, given this mutation is part of the 'nice trick' that saves it from having to add event listeners on each patch. But sharing event handler data between vnodes seems like a normal thing to do. (In my case I was rendering a set of radio buttons, each having the same change handler based on the event target value.)  

Perhaps a warning should be added to the readme, if there is no way around this?

**Comment by paldepind** [comment]
In general modules can modify the data object if they want to. The only solution would be to copy the object. But that would affect performance negatively.

> But sharing event handler data between vnodes seems like a normal thing to do. (In my case I was rendering a set of radio buttons, each having the same change handler based on the event target value.)

That certainly sounds like a reasonable thing to do. Would the code be more complicated if you weren't reusing a single change handler?

> Perhaps a warning should be added to the readme, if there is no way around this?

I agree. Probably with an example on what not to do and what to do instead?

**Comment by ericgj** [comment]
> Would the code be more complicated if you weren't reusing a single change handler?

As it turns out ... not really. Having a single handler function shared between nodes is no problem, it's having a single `{change: handler}` (or other event) _object_ shared between nodes. So it's just a matter of attaching the handler to a new object when constructing each node. The next time I probably will use array-based handlers to sidestep the whole issue.

I will work on an example to add to the readme.
