### ISSUE TITLE
prepatch/postpatch hooks not called on modules

### ISSUE THREAD

**Issue by yelouafi** [paldepind/snabbdom#37]
the 'prepatch/postpatch' is only called on hooks attached to specific vnodes but not on generic modules.
The hooks are also not called on the first patch operation (element creation)

**Comment by paldepind** [comment]
If I understand you correctly this is similar to @25?

> The hooks are also not called on the first patch operation (element creation)

I don't consider element creation a patch operation.

None of this is set in stone. The current behaviour has been sufficient for me. If you have a convincing use case that is not covered by the current implementation I'd be very interested in seeing it :smile:

**Comment by yelouafi** [comment]
> If you have a convincing use case that is not covered by the current implementation I'd be very interested in seeing it 

Actually i wanted to implement a module that can exposes a kind of top-down "scope". The concept is similar to JavaScript prototypal inheritance, starting from the top vnode, each vnode can add or override properties in the scope; the attributes on the scope could be used by modules to handle cross-cutting concerns like automatically wrapping the result of an event handler in a certain context (logging for example) without the need of passing explicitly this info between view functions. Something similar to [Aspect Oriented Programming](https://en.wikipedia.org/wiki/Aspect-oriented_programming)

For this i need to 

- reset the scope on the start of the global patch operation
- going top-down read relevant info from the vnode and copying them into the scope.

So i need to listen for prepatch operation on all nodes. I tried the couple {create, update} but didn't work: create doesn't fire top-down but down-top; the create hook is fired starting from the innermost children. and the update hook isn't invoked on the newly created vnode.

i thought that prepatch/postpatch would be a consistent way to hook on every patch operation since there is no separate create method in snabbdom.

**Comment by paldepind** [comment]
Ok. I think I partly understand. You need to go top-down on the vnode tree and update the values in the specific scopes?

Would it work if you traversed the entire tree in the `post` hook? The `post` hook is called after the entire patch process is done?

**Comment by yelouafi** [comment]
>Would it work if you traversed the entire tree in the post hook? The post hook is called after the entire patch process is done?

Yes, it would. But do you think this post-traversal wont have a visible impact on the performances ? if not, then i think this is even better and more reliable than maintaining a state machine that would depend on the order of traversal of the algorithm (perf. doesn't matter for dev. concerns like logging but the scope would be utils for other things like localisation ...)

**Comment by paldepind** [comment]
I wouldn't worry about performance. I highly doubt traversing the vnode tree is going to be a bottleneck. Also you save some performance in that you wont have to maintain the state machine. It sounds like a cleaner solution to me.

If you're curious you could try adding a hook to Snabbdom and do a benchmark of using it versus your own traversal.

Do I understand you correctly in that you want to copy everything in a parent scope to a child scope? Why not instead find the correct value in scope when it is requested? And then maybe cache it?

**Comment by yelouafi** [comment]
>Do I understand you correctly in that you want to copy everything in a parent scope to a child scope? 

No, actually it's more like building a prototype chain of objects; each child can override some properties in the parent scope.

>Why not instead find the correct value in scope when it is requested? And then maybe cache it?

Can you elaborate on this ?

**Comment by paldepind** [comment]
> Can you elaborate on this ? 

I'm guessing that my suggestion didn't make any sense. I meant something similar to when a property is accessed on an object in JS. First you check the object itself for the property, then it's prototype, then the prototypes prototype and so on.

I'm closing this issue. Feel free to reopen it if relevant.
