### ISSUE TITLE
Hero Module - oldVnode not calculating its bounding rectangle

### ISSUE THREAD

**Issue by SkaterDad** [paldepind/snabbdom#41]
#### Issue
I'm attempting to get a hero transition working using Cycle.js with cycle-snabbdom (which uses snabbdom 0.2.7).

The hero module executes all of the appropriate hooks, but when it tries to calculate `oldRect = oldElm.getBoundingClintRect()`, all of the keys are = 0.  The `newElm` calcs are all good.  Naturally the incorrect oldRect causes the translation calcs to be wrong, resulting in very weird transitions.

#### Test App Setup
My setup is very simple:  just a checkbox which toggles two vNodes.  Do you see anything wrong with these vnode definitions (falseView, trueView) for using with the Hero module?

If you think this should work, I can move this issue over to cycle-snabbdom to see if it's an implementation issue.

CSS:
```css
    body {
      background-color: rgb(230,230,230);
      margin: 0;
      width: 100%;
    }
    .hero {
      transition: transform 1s, opacity 1s;
    }
```
Cycle App:
```javascript
import Cycle from '@cycle/core';
import {h, makeDOMDriver} from 'cycle-snabbdom';

const falseView =
  h('div',
    {
      style: {width: '100px', height: '100px', backgroundColor: 'pink', margin: '1rem'},
      hero: {id: 'test-hero-simple'},
    },
    [h('span.smalltext.hero',
      {
        hero: {id: 'test-hero-simple'}
      },
      `Simple Box`)
    ]
  )

const trueView =
  h('div',
    {
      style: {width: '300px', height: '200px', backgroundColor: 'pink', margin: '5rem'},
    },
    [h('span.bigtext.hero',
      {
        hero: {id: 'test-hero-simple'}
      },
      `Simple Box`)
    ]
  )

function main({DOM}) {
  let vTree$ =
    DOM.select('input').events('change')
      .map(ev => ev.target.checked)
      .startWith(false)
      .do((x) => {console.log(`Checkbox value changed to ${x}`)})
      .map(toggled =>
        h('div', {}, [
          h('input#box1', {attrs: {type: 'checkbox'}}), 'Toggle me',
          toggled ? trueView : falseView,
        ])
      )

  return {DOM: vTree$}
}

Cycle.run(main, {
  DOM: makeDOMDriver('#main-container', [
    require(`cycle-snabbdom/node_modules/snabbdom/modules/class`),
    require(`cycle-snabbdom/node_modules/snabbdom/modules/hero`),
    require(`cycle-snabbdom/node_modules/snabbdom/modules/style`),
    require(`cycle-snabbdom/node_modules/snabbdom/modules/props`),
    require(`cycle-snabbdom/node_modules/snabbdom/modules/attributes`),
  ]),
})
```

#### Chrome Debugger Data
The `oldElm` looks like this when inside the `post()` function.  I find it strange that it says `parentElement: null`.
```
oldElm: span.smalltext.hero
accessKey: ""
attributes: NamedNodeMap
baseURI: null
childElementCount: 0
childNodes: NodeList[1]
children: HTMLCollection[0]
classList: DOMTokenList[2]
className: "smalltext hero"
clientHeight: 0
clientLeft: 0
clientTop: 0
clientWidth: 0
contentEditable: "inherit"
dataset: DOMStringMap
dir: ""
draggable: false
firstChild: text
firstElementChild: null
hidden: false
id: ""
innerHTML: "Simple Box"
innerText: "Simple Box"
isContentEditable: false
lang: ""
lastChild: text
lastElementChild: null
localName: "span"
namespaceURI: "http://www.w3.org/1999/xhtml"
nextElementSibling: null
nextSibling: null
nodeName: "SPAN"
nodeType: 1
nodeValue: null
offsetHeight: 0
offsetLeft: 0
offsetParent: null
offsetTop: 0
offsetWidth: 0
...(irrelevant 'on...' events)...
outerHTML: "<span class="smalltext hero" style="transform-origin: 0px 0px 0px; opacity: 1;">Simple Box</span>"
outerText: "Simple Box"
ownerDocument: document
parentElement: null
parentNode: null
prefix: null
previousElementSibling: null
previousSibling: null
scrollHeight: 0
scrollLeft: 0
scrollTop: 0
scrollWidth: 0
shadowRoot: null
spellcheck: true
style: CSSStyleDeclaration
tabIndex: -1
tagName: "SPAN"
textContent: "Simple Box"
title: ""
translate: true
webkitdropzone: ""
__proto__: HTMLSpanElement
```
Which results in this oldRect:
```
oldRect: ClientRect
   bottom: 0
   height: 0
   left: 0
   right: 0
   top: 0
   width: 0
```

Thanks!

**Comment by SkaterDad** [comment]
I was able to successfully port the official hero example to Cycle today, and it worked well.

This leads me to believe the issue is specific to my code above, and is not the fault of `cycle-snabbdom`'s implementation.

**Comment by SkaterDad** [comment]
Finally solved this.

If the hero nodes are inside of another node (like a `span` inside of a `div`), the containing element needs to use the `remove` style module hook.  Without that, the hero module seemed unable to calculate the exiting hero node's position.

If I get time, I'll make an attempt to write documentation for this and submit a PR, unless you've already got some underway.

**Comment by paldepind** [comment]
> If the hero nodes are inside of another node (like a span inside of a div), the containing element needs to use the remove style module hook. Without that, the hero module seemed unable to calculate the exiting hero node's position.

If the hero node is inside another node and they're both removed at the same time then you will have to delay the removal of the containing node (for instance by using the `remove` style hook). Otherwise the hero node will be detached from the DOM once the hero module calls `getBoundingClintRect` on it. And that will result in an incorrect rectangle.

> If I get time, I'll make an attempt to write documentation for this and submit a PR, unless you've already got some underway.

That would be nice. I'd highly appreciate it.

**Comment by SkaterDad** [comment]
Thanks for verifying that.

So far I'm struggling my way through applying this concept to a more complex view which I had already laid out, figuring out where I need `position: relative` and `position: absolute` so that elements don't shift their positions before the hero calculations take place.  I'll get there eventually, but I'm certainly cursing the DOM and CSS right now! :laughing:

**Comment by SkaterDad** [comment]
@paldepind Are you open to major changes to the `hero` module?  I'm happy to release my own module, but if you like what I describe below we could build this into your library.

I have been modifying the `hero` module to suit my needs, in an attempt to make it more flexible and less finicky.

My goal is to be able to hero transition an element without doing any special modification to the parent nodes or child nodes.  I'm accomplishing part of this by saving the node's rectangle in the hero module destroy function.
```javascript
function destroy(vnode) {
  var hero = vnode.data.hero;
  if (hero && hero.id) {
    vnode.lastRect = vnode.elm.getBoundingClientRect() //NEW - save the bounding rectangle to a new property on the vnode
    removed[hero.id] = vnode;
  }
}
```

Then I use that saved value in the post() function.
```javascript
    if (oldVnode) {
      newStyle = newElm.style;
      oldElm = oldVnode.elm;
      oldStyle = oldElm.style;
      newRect = newElm.getBoundingClientRect();
      oldRect = oldVnode.lastRect; //NEW - USE PREVIOUSLY SAVED BOUNDING RECTANGLE
```

With these changes, I no longer need the parent nodes to use the `style` module's `remove/destroy` hooks, since the layout is still completely in tact when the calc is performed.

I have a few more changes I'm playing around with to deal with hero nodes that have margins or relative sizing, etc... I still have a lot of testing to perform against more layouts and node types.

**Comment by paldepind** [comment]
@SkaterDad I think that is a splendid idea. Getting the bounding rectangle in the `destroy` hook makes a lot of sense since the destroy hook is invoked before any elements are removed from the DOM. I should have thought of that myself :)

I think "finicky" is a quite fair word to use about the current state of the hero module. I think your idea is a great step away from that. I'd be very happy to accept major changes to the hero module!

**Comment by SkaterDad** [comment]
Quick update on this.

Text nodes (like span, h1, p) proved a bit more difficult to translate properly without distortion.  I finally cracked it, though, after much experimentation and many more lines of code.

My test page works with the following text cases (all of them move to divs on different parts of the page):

1. `H1` which changes `font-size` and `text-align` from left to right.
2. `span` which stays same size, but changes justification from left to center in smaller div.
3. `p` which stays same size and justification.

I need to clean up the code a bit before I'll push it to my forked snabbdom repo, and after that I'll submit a PR.

**Comment by SkaterDad** [comment]
Pushed more updates to my WIP hero module. (see link above)

I ended up copying the entire getComputedStyle() object for each node in `destroy()`.  CSS the way it is, quite a lot of properties can be lost when moving a node to the document body.  Instead of chasing down edge cases, this seemed more robust.

**Comment by paldepind** [comment]
> Could you do a brief review of this code before I submit the PR? I wasn't sure if you had specific formatting/style requirements.

It looks good to me. Feel free to open a PR :)
