### ISSUE TITLE
Supporting other platforms other than the DOM

### ISSUE THREAD

**Issue by TylorS** [paldepind/snabbdom#47]
I was wondering if it would be possible, and if it is, if it would be *desirable*, to split the codebase up a little bit to allow for alternative platforms. Snabbdom being a facility to this. 

I'm currently working on my own framework, [Motorcycle.js](https://github.com/motorcyclejs), and I'd like to add support for [nativescript](https://www.nativescript.org/) in the near future. I was hoping to avoid the need to for creating something entirely specific for Motorcycle if possible, and thought it might be possible to rework Snabbdom to be able to organize this.

Love to hear the thoughts on this.

**Comment by paldepind** [comment]
If I understand you correctly you're suggesting to split the DOM specific parts of Snabbdom from the non-DOM specific parts? What would you then put in place of the DOM specific parts? I'm not familiar with NativeScript? But would that make it possible to use parts of Snabbdom with the UI APIs from NativeScript?

**Comment by TylorS** [comment]
Yeah, that would be my desire. I haven't investigated this too far yet to be honest.
I was thinking it may be possible to have Snabbdom to provide an API or interface that allows for different backends to cooperate with it. i.e. `appendChild()`, `updateProps()` etc.

The ultimate goal, would being able to share a considerable amount of UI code between web and mobile, sort of like React/React-Native without any of the React stuff. I would be highly motivated to create a working backend for NativeScript. 

Again, this is something I haven't fully investigated, I wanted to feel out some of the possible ways to go first. This would be a project I would plan to start in the next couple weeks, after I'm able to bring Motorcycle to v1.0.

If this isn't something you're interested in, no worries. Just figured it couldn't hurt to ask :smile:

**Comment by paldepind** [comment]
I assume it would be possible. One could identify all the places where Snabbdom interacts with the DOM, and then inject those methods into Snabbdom. Given the small size of Snabbdom that would certainly we feasible. If it is possible to implement equivalents of the DOM functions with NativeScript then that might be a worthwhile approach.

But then there is the modules. Some of those are very HTML and CSS specific.

**Comment by user471** [comment]
:+1: I am also looking for DOM Diff library whitch could be used with any dom and not only html.
I think, instead of using DOM methods directly there could be some abstraction over it.

DomMonipulator = {
     getChildNodes = ...
     appendChild = ...
     ...
}
And different implementations HtmlDomManipulator, NativeDomManipulator, etc.

**Comment by paldepind** [comment]
Yes @user471. I had the same thing in mind in my previous comment.

**Comment by blvz** [comment]
FWIW
https://github.com/dekujs/deku

**Comment by user471** [comment]
@blvz I don't see anything related to the problem. In code it used html document directly.

**Comment by blvz** [comment]
@user471 Take another look.

> Deku consists of 4 modules packaged together for convenience:

> - element: Creating virtual elements
> - diff: Computing the difference between two virtual elements
> - dom: DOM renderer
> - string: HTML string renderer

There's two renderers:
- [DOM renderer](http://dekujs.github.io/deku/docs/api/dom.html), which uses `document.createElement` etc..
- [String renderer](http://dekujs.github.io/deku/docs/api/string.html) which renders/builds to a string, for server side stuff. No `document`.

The way it's built, it's easy to create more renderers, like canvas or NativeScript.

**Comment by user471** [comment]
>The way it's built, it's easy to create more renderers

You can create renderer, but you cannot reuse patch logic and it's most important part.

**Comment by blvz** [comment]
@user471 The [patch](https://github.com/dekujs/deku/blob/master/src/dom/patch.js) is part of the DOM renderer module. It just implements the abstraction created from the [diff](https://github.com/dekujs/deku/blob/master/src/diff/index.js#L11-L23).

[This](https://github.com/dekujs/deku/blob/master/src/diff/index.js#L11-L23) and [this](https://github.com/dekujs/deku/blob/master/src/dom/patch.js#L30-L43) are almost the same thing you've [mentioned](#issuecomment-168324781).

**Comment by user471** [comment]
Thank, now it looks exactly what I want. Is there any documentation about this feature? 
Also, according to http://vdom-benchmark.github.io/vdom-benchmark/ deku seems much slower than snabbdom

**Comment by blvz** [comment]
@user471 All [documentation is here](http://dekujs.github.io/deku/index.html), but I think you'll be better off cloning the DOM renderer and overriding from there.

I mentioned deku as a reference, since they abstracted the renderers. I'm not endorsing it, since I prefer and use snabbdom. But if deku already does what you want, maybe you can live with some minor performance trade offs for now.

**Comment by willin** [comment]
@blvz http://dekujs.github.io/deku/index.html 404 Not Found

**Comment by blvz** [comment]
@willin well, that was more than _2 years ago_. you can still find it here, though: [anthonyshort/deku](https://github.com/anthonyshort/deku)
