### ISSUE TITLE
Can't add to child array from "onmessage" in websockets application.

### ISSUE THREAD

**Issue by dschalk** [paldepind/snabbdom#49]
I am working on the third page of a project I call  "Javascript Monads". The page is called  "Javascript Monads Part 2" and is the third item down on the menu at http://schalk.net . It runs at http://schalk.net:3093/ .

I'm stuck on the usually trivial task of writing code to display chat messages. main.js starts with
```javascript
"use strict";

import cow from './cow';
import snabbdom from 'snabbdom';
import h from 'snabbdom/h';

var newMessage = (v,mon) => {
  let ar = mM11.x;
  ar.push(h('div', mM16.x));
  mM11.ret(ar);
  return mon;
};
mM16.ret('One').bnd(newMessage);
```
When the web page is refreshed, "One" appears as expected.
```javascript
      h('input', {style: inputStyle1, on: {keydown: updateLogin},  } ),
      h('div', {props: {id:'chat'}}, mM11.x ),
```
mM11 and mM16 are instances of Monad which is made available by a script tag in index.html. I had the same problem when I didn't use the Monad instances, so I hope they aren't too much of a distraction. I'll modify the code if you like. mM11.x is the value of mM11, and is an array created by h('div', ' One '  ) when the page loads and mM16.ret('One').bnd(newMessage) executes. The screen shot "After_reload.png" shows that everything succeeds as intended. mM11.x is shown in the console log in the screen shot.
When I run similar code from "onmessage" with "Two"  hard coded in and "Three" received from the server,  nothing appears on the webpage. The console log shows that mM11.x contains three objects, but the ones with text "Two" and "Three" show "elm: undefined" instead of "elm: div".
Here's the code in "onmessage":
```javascript
          case "CD#$42":
            mM16.ret('Two').bnd(newMessage);
            mM16.ret(extra).bnd(newMessage).bnd(update);
          break;
```
As I mentioned above, I get the same behavior without using Monad instances, but I'll include the definition of Monad anyway. What I haven't been able to figure out is why "newMessage()" works as intended at the top of the file, but pushes an object with "elm: undefined" when called from inside "onmessage".
```javascript
  class Monad {
    constructor(z) {

      this.x = z;

      this.bnd = (func, ...args) => {
        return func(this.x, this, ...args);
      };

      this.ret = a => {
        this.x = a;
        return this;
      };

      this.fmap = (f, mon = this, ...args) => {      
        mon.ret( f(mon.x, ...args));
        return mon;

      };
    }
```
 The browser screenshots are from Chrome running http://schalk.net:3093 in Ubuntu 14.04. The code repository is at https://github.com/dschalk/websockets-monads-part2. 
I am a refugee from React (See https://www.fpcomplete.com/user/dschalk/Websockets%20Game%20of%20Score?show=tutorials, running at http://schalk.net:3015/). I love what you and your collaborators are doing. I expect to eventually use pure functions and immutable data in my Javascript Monads project, but not until an application gets so complex that I see an advantage in doing so. 
Here are the screen shots:
[main js](https://cloud.githubusercontent.com/assets/2214003/12031116/560c744a-add6-11e5-9e53-befdbf676011.png)
[after_browser_refresh](https://cloud.githubusercontent.com/assets/2214003/12031120/5ad7c2ea-add6-11e5-976d-29d955bb1f04.png)
[after_logging_in_as_d](https://cloud.githubusercontent.com/assets/2214003/12031122/5e0284d2-add6-11e5-9cae-40e22d7449ed.png)
[after_sending_the_message_three](https://cloud.githubusercontent.com/assets/2214003/12031126/625aec5e-add6-11e5-823d-fcefb18921a0.png)

**Comment by dschalk** [comment]
![after_sending_the_message_three](https://cloud.githubusercontent.com/assets/2214003/12014335/bda0cd1a-acf8-11e5-94ae-c5469ad1caf7.png)

**Comment by dschalk** [comment]
I added mM16.ret('Two').bnd(newMessage); at the top of main.js. Now, One and Two are displayed when the browser is refreshed. Here's a screen shot of the top of main.js:
[new_main js](https://cloud.githubusercontent.com/assets/2214003/12016635/72e15d76-ad1b-11e5-85d6-2c2dfd085b6b.png)

**Comment by dschalk** [comment]
I simplified the code to zero in on (my major malfunction || bug). There are no longer any ersatz monads. Here is the relevant switch clause in "onmessage":
```javascript
          case "CD#$42":
            newMessage('Two');
            newMessage(extra);
            update0();
          break;
```
The screen shots show the definition of "newMessage" and the objects that get created in the switch clause.  They have "elm: undefined" rather than "elm: li".
[main js](https://cloud.githubusercontent.com/assets/2214003/12030855/f722eaf2-add2-11e5-925f-00ee381b2bba.png)
[after_browser_refresh](https://cloud.githubusercontent.com/assets/2214003/12030856/fb8f33d4-add2-11e5-9cb3-c76be036d54d.png)
[after_logging_in_as_d](https://cloud.githubusercontent.com/assets/2214003/12030859/00f16b58-add3-11e5-9a92-7a078b4b3568.png)
[after_sending_the_message_three](https://cloud.githubusercontent.com/assets/2214003/12030863/070e9362-add3-11e5-8126-6372d0214424.png)

**Comment by dschalk** [comment]
UPDATE: I am able to print messages by filling an array named "ar7" with strings from both the top of main.js and from inside of  "onmessage" and then running this function:
```javascript
var ar8 = function ar8(x) {
  let ar = [];
  let keys = Object.keys(ar7);
  for (let k in keys) {
    ar.push(ar7[k]);
    ar.push(h('br'));
  }
  return ar;
}
```
Inside of "view", I have the line:
```javascript
      h('div', {props: {id:'chat3'}}, ar8() ),
```

**Comment by paldepind** [comment]
Where in the code are you creating the view and invoking `patch`?
It looks like `messageAr` is a global arrays of vnodes that you are mutating?
Are you reusing `messageAr` across several calls to `patch`?

Another thing. Are you aware of [fantasy-land](https://github.com/fantasyland/fantasy-land)? It's a specification for, among other things, monads in JavaScript. It might be interesting to you since you're implementing monads in JavaScript.

**Comment by dschalk** [comment]
I create the view starting on line 60. The code is next door at [https://github.com/dschalk/websockets-monads-part2](https://github.com/dschalk/websockets-monads-part2). patch is invoked directly 58 times in main.js and indirectly in "update" and "update0".

**Comment by dschalk** [comment]
I'll make this as concise and clear as possible. 

I put these lines near the top of "onmessage":
  let test_h = h('div', 'Hello from onmessage' );
  console.log(test_h);

Here is the screen shot showing that the object returned by h has "elm: undefined" instead of "elm: div".
[after_login_and_roll](https://cloud.githubusercontent.com/assets/2214003/12069300/98527c7a-aff5-11e5-9c90-17ce518c9931.png)

**Comment by dschalk** [comment]
Oops! The above code doesn't work at the top of main.js now. 

I have a satisfactory way to display chat messages. I don't think this issue is helpful. I suggest that you close it.

**Comment by paldepind** [comment]
> I put these lines near the top of "onmessage":

>```let test_h = h('div', 'Hello from onmessage' );
console.log(test_h);```

> Here is the screen shot showing that the object returned by h has "elm: undefined" instead of "elm: div".

Yes. That is expected. `h` returns a virtual node. The `elm` property contains the actual DOM element that has been created from the virtual node. But the creation of the DOM element happens in `patch`. Thus only after the virtual node has been through `patch` will the `elm` property be set.

Also one should not mutate virtual nodes. Then how would you pass the state of the old view to `patch`? Additionally it does not work if one reuses the same virtual DOM tree several times as the second argument to `patch`.

Does the above make sense? Does it help in any way?

**Comment by dschalk** [comment]
http://schalk.net:3093/ is working. A multiplayer game is working, displaying a score board and chat messages to all members of each group. Snabbdom works like a charm, facilitating much functionality in not many lines of code. 

My solution is to populate an array of strings with messages or scoreboard data coming in from the server, then call a function from inside of view that uses the string array to generate alternating text nodes and <br /> nodes. These are freshly produced each time view is called, so nothing is being mutated. 

I'm sure your comments make sense and I am eager to understand them.  I think you pointed me in the right direction by informing me that patch sets the elm property. I have tried to find an explanation of diff & patch & render to no avail. Presentations and tutorials purporting to explain virtual DOM actually treat it as a black box, and just demonstrate how to use the API. Of course, the best explanation is in the library code, but that can be a hard nut to crack. I just now tried to find the definition of "patch" in the Snabbdom Github repository and missed it, so I will methodically try again. Any suggestions as to how I might approach really understanding your library or Matt Esch's would be much appreciated. I suspect the Facebook method is overly complex. 

You are so gracious and kind for taking the time out of your busy life to point me in the right direction. Thank you.

**Comment by dschalk** [comment]
The `cows` and the `horses` are here.

**Comment by dschalk** [comment]
Now that I have some experience with Snabbdom, README.md no longer causes cognitive overload. On the contrary,  it is lucid, thorough, and very helpful. 

One suggestion: I have been experimenting and still haven't succeeded on making `onfocus` or some variation of `on: focus` cause focus to go to a sign in text box. Maybe `README.md` ought to have an example or instructions about directing focus to `input` boxes.

**Comment by dschalk** [comment]
RESOLVED

The monads handle websockets chat messages with two reserved monads, `mMmsg` for holding the array of all chat message strings that come in from the server, and `mMmessage` for holding the list of Snabbdom vnodes. The Snabbdom chat message display is generated by placing the array `mMmessage.x` in `view()` as children of a div. Here is the definition of the function `mMmessage` calls with its `bnd` method:
```javascript
  var updateMessages = function msg(x,mon) {  
    mon.ret([]);
    let ar2 = mMmsg.x;
    let keys = Object.keys(ar2);
    for (let k in keys) {
      mon.bnd(push, ar2[k])
      .bnd(push, h('br'));
    }
    return mon;
  }
```
Inside of `onmessage`, chat messages get intercepted and processed as follows:
```javascript
  case "CD#$42":
    gameArray.splice(0,3);
    let message = gameArray.reduce((a,b) => a + ", " + b)  
    let str = sender + ': ' + message;
    mMmsg
    .bnd(push,str)
    .bnd( () => mMmessage
    .bnd(updateMessages)
    .bnd(update) );
  break;
```
After updating itself with the new message comming in from the server, `mMmsg` hands over processing to `mMmessage`. `mMmessage` then calls `updateMessages` with its `bnd` method; and finally, `mMmessage` calls `update`, which runs `patch`. That's all there is to it. The array mMmessage.x sits quietly in view() as an array of children of its parent div.

I thought I stumbled across a bug in Snabbdom, but I was mistaken. I can now answer the question, "Does the above make sense? Does it help in any way?" Yes and Yes, it helped greatly. Thanks again.

**Comment by dschalk** [comment]
I don't recommend that you look at my monads project before February, 2016. It is in flux.

**Comment by paldepind** [comment]
I'm glad you got the issue resolved @dschal :smile:

I'm curious if you have any ideas about how to improve the documentation of Snabbdom. When I come to think of it it pretty much assumes that one already knows what a virtual DOM library is. Where there any specific stumbling blocks with regards to Snabbdom that the documentation could clarify? Or did you find any tutorials that helped you understand virtual DOM better?

**Comment by dschalk** [comment]
Parts 1, 2, and 3 of the JS-monads project are done.  Part 1 introduces "Monad", which I defined as a class for convenience. I can refer to "instances". I feel a little uncomfortable about that, especially since Douglas Crockford and Kyle Simpson agree that Javascript should not have ersatz classes to sugar-coat what is actually prototype scoping.

I think you can save time by going directly to [github.com/dschalk/JS-monads-part3](https://github.com/dschalk/JS-monads-part3). README.md gives an  overview of the code. But before you examine any code, I suggest that you see what it does at [schalk.net:3093](http://schalk.net:3093). That site features code and explanations, along with the multi-player websockets app. There is a link to it and the first two parts of the series at [http://schalk.net](http://schalk.net).

The very simple Monad and MonadIter instances seem to be doing what JS6 Promises and Generators do, without the error handling. So far, my apps don't make ajax calls or interact with data bases, so error handling seems like it would be a senseless drag on performance. 

I'm glad that you are going to look at my project. The more you share your impressions with me, the happier I will be. Don't worry about hurting my feelings. If it seems just too devastating to broadcast to the world, you can send it to fpschalk@gmail.com. Otherwise, I think it would be kind to let other people who might see this learn from whatever impressions you share.

Anyway, here it is. The next installment will probably feature an error-handling monad. I'm not sure what I want it to do. The Haskell Maybe monad ends all subsequent code evaluation, sending the value Nothing to the end of the chain. I would want to also send some information about the source of the error, along with any error message that was returned.

##Regarding your question:
My first involvement with Javascript, beyond cut and pasted buttons that change on hover and click, was a NodeJS version of the game of Score. The consensus back then seemed to be that it would be a waste of time to try to make an app function correctly in all of the major browsers when JQuery already had that covered. I didn't understand the DOM, let alone the concept of a virtual dom for diffing and patching. When I first looked at your code, I vaguely knew about getElementById and didn't know anything about removing and creating elements on the DOM. The code looked confusing.

I would like to see the simplest possible virtual DOM diff & patch algorithm; one without hooks that performs elementary remove and create operations. I don't see such a thing in "Javascript The Definitive Guide" or in other book or tutorial I have encountered. If you know where I could find it, please tell me, or put a link in your README.md file. Otherwise, I think you could help many people by writing the elementary algorithm yourself. 




I think you can save time by going directly to [github.com/dschalk/JS-monads-part3](https://github.com/dschalk/JS-monads-part3). README.md gives an  overview of the code. But before you examine any code, I suggest that you see how it performs at [schalk.net:3093](http://schalk.net:3093). There is a link to it and the first two parts of the series at [http://schalk.net][http://schalk.net).

**Comment by hville** [comment]
@paldepind this should probably go in another thread but since you asked about ideas for the documentation here are a few things that got me stuck and/or puzzled at first:
* How to get access to actual DOM node through the *hooks*. The hook section shows that the callbacks are passed a *vnode*. It is only in this thread that I have learned about the `.elm` property.
* Related to the point above, some words about the `vnode` object structure. 
* On my first attempts I tried `patch(document.body, myNode)` and that always failed with criptic errors. I ended up creating a dedicates `<div>` container similar to the examples. Looks like *snabbdom* uses the body tag to store info. A warning in the docs on a specific patch Error would help.
* I still don't quite get the *modules* concept. I looked at the code for the pre-defined ones but they are quite different one from another and the essence of it has not infused into my brain yet.

Hope this helps.

**Comment by dschalk** [comment]
Thanks Hugo.  

Answering Simon's question: "Or did you find any tutorials that helped you understand virtual DOM better?"  Yes. The free Egghead video at https://egghead.io/series/cycle-js-fundamentals shows the creation of a virtual dom element from scratch, before bringing in Cycle.js to do it with the virtual-dom library's "h" function. André Staltz  is a great teacher, but he hasn't convinced me that bringing in an observer library (he likes RxJS) is worth having to write extra code, or worth the drag on browser resources.

**Comment by dschalk** [comment]
A cyclejs version of the websockets game is at https://github.com/dschalk/js-monads-cycle-1.git

**Comment by TylorS** [comment]
I wouldn't take much notice of `cycle-most-snabbdom`.
That work has been moved to [motorcycle-dom](https://github.com/motorcyclejs/dom).

**Comment by dschalk** [comment]
Thanks.

**Comment by paldepind** [comment]
@dschalk Very exciting to hear that you had a great experience using Motorcycle.js.

**Comment by dschalk** [comment]
[https://github.com/dschalk/JS-monads-part4/blob/master/README.md](https://github.com/dschalk/JS-monads-part4/blob/master/README.md)

**Comment by dschalk** [comment]
@paldepind Re: "When I come to think of it it pretty much assumes that one already knows what a virtual DOM library is. " It's unfortunate that your assumption wasn't justified in my case. I have no formal education in computer programming, and I foolishly let JQuerry insulate me from more directly manipulating the DOM  for way too long. In my latest monads demo, running at http://schalk.net:3077 , the numbers in the game display are not hard coded into the html. I set and get the numbers on the fly as the game progresses, or as players traverse the history of the numbers display.  As I become increasingly comfortable with Motorcycle.js, I am, at long last, learning what a virtual DOM library is. Thanks for your encouragement.
