### ISSUE TITLE
vnode init hook not documented

### ISSUE THREAD

**Issue by sprat** [paldepind/snabbdom#54]
It seems that the vnode's init hook is not documented. Is it safe to use in my library?

**Comment by paldepind** [comment]
Yes. The `init` hook is safe to use. It not being in the documentation is an omission.

**Comment by paldepind** [comment]
I have now added documentation about the `init` hook. Thank you for catching this mistake. I had completely missed the `init` hook when writing the hook documentation.

**Comment by sprat** [comment]
Thanks
