### ISSUE TITLE
init and prepatch module hooks?

### ISSUE THREAD

**Issue by sprat** [paldepind/snabbdom#55]
I miss the init and prepatch hooks for a module of mine. I am wondering why some vnodes' hooks are not exposed as module hooks? Can this be fixed in the API?

Or maybe I missed something... I would like to process the children of vnodes before the vnodes are rendered: how we can do that for any vnode?

**Comment by sprat** [comment]
I finally think I need to use a thunk. However, I've found a bug in the patch function when using a thunk:

```javascript
if (oldVnode instanceof Element) {
      if (oldVnode.parentElement !== null) {
        createElm(vnode, insertedVnodeQueue);  // <------ here
        oldVnode.parentElement.replaceChild(vnode.elm, oldVnode);   // <------ here
      } else {
        // ...
      }
    }
    // ...
```

The 2 lines should be (or be something like that):
```javascript
        vnode.elm = createElm(vnode, insertedVnodeQueue);
        oldVnode.parentElement.replaceChild(vnode.elm, oldVnode);

```

**Comment by sprat** [comment]
In fact, I encountered many bugs when using thunks. Since there's already an issue filed for thunks, I've added my comments on this issue : see https://github.com/paldepind/snabbdom/issues/40

I still think that having init and prepatch hooks for modules would be cool, so I keep this issue opened for that purpose.

**Comment by paldepind** [comment]
> I would like to process the children of vnodes before the vnodes are rendered: how we can do that for any vnode?

Does the `create` hook work for you? It is invoked once the element for a virtual node and is children has been created but before it has been inserted into the DOM.

**Comment by sprat** [comment]
No, in fact I would like to process *vnode* children, not DOM children...

**Comment by paldepind** [comment]
Yes. The `create` hook gives you the vnode and you can access its vnode children through it.

**Comment by sprat** [comment]
Yes, we have access to vnode children, but they are already rendered when `create` is called. So I can't transform them before they are rendered, a bit like a thunk.

Is there a reason why not all hooks are available both as module hooks and node hooks? I think it would simplify the code.

**Comment by paldepind** [comment]
> Is there a reason why not all hooks are available both as module hooks and node hooks? I think it would simplify the code.

I've added all hooks on a per need basis. The hooks that has never been needed to be available globally hasn't been added as module hooks. This isn't set in stone though. A similar question was asked in #37.

If you have a convincing use case then the `init` hook should be made available as a global module hook.

**Comment by sprat** [comment]
I don't have a use-case anymore as I now use thunks. But, when I started using your library, I was planning to implement a sort of thunk feature on top of these module hooks. In fact, i wanted to add support for "generating" functions as children, that I would call just before the node rendering.

I must admit that I'm not satisfied with the current implementation of thunks in snabbdom, even after my pull-request, so these hooks may prove useful later. Maybe the thunk feature may be implemented on top of these hooks? If this is the case, all the thunk-related traversal code could probably be removed from the snabbdom core.

These module hooks are an attractive feature of your API. It's maybe what's attracted me to snabbdom in the first place. I'm pretty sure people will find creative uses of any hook you may expose ;)

**Comment by Guria** [comment]
seems I am the one who needs `init` module hook too. will try to prepare my use case soon

**Comment by paldepind** [comment]
I am closing this. Feel free to reopen it with a use case. @Guria or anybody else who might have one.

**Comment by doesdev** [comment]
A use case I have, unless I'm overlooking a better way, is to add child vnode(s) to the vnode being patched from a module. In testing this only works from the init hook.

It's highly likely that there is a better way of doing this in a modular fashion, but I would very much like to be able to do this as a module. My specific use case is adding popovers to given elements.

Is there a better way, or should the init hook be exposed to modules?
