### ISSUE TITLE
Save excursion

### ISSUE THREAD

**Issue by katyo** [paldepind/snabbdom#63]
When we change property `value` of text inputs, usually we would like to save cursor position, selection range and focus of element, which is in focus.
In my experience, there is two cases, which assume different workarounds:
1. The new `value` is same as the `value` of focussed input: We may simply don't assign new value without any extra work.
2. The new `value` is different from current `value` of focussed input (for example, the value was changed by controller): We need get *selection* before changing value, and set selection after that. If *selection* is also set using properties, we must use it instead of current *selection*.
I tried to change **props** plugin to do that. Is it appropriate way? Or I need to create different plugin to work with inputs.
At the moment, all my fixes is quite simple:

```javascript
function updateProps(oldVnode, vnode) {
  var key, cur, old, elm = vnode.elm,
      oldProps = oldVnode.data.props || {}, props = vnode.data.props || {},
      preserveExcursion = "value" in props && typeof elm.selectionStart === "number" &&
                          document.activeElement === elm && props.value !== elm.value,
      /* save excursion */
      selection = preserveExcursion ? [
        typeof props.selectionStart === "number" ? props.selectionStart : elm.selectionStart,
        typeof props.selectionEnd === "number" ? props.selectionEnd : elm.selectionEnd
      ] : null;
  for (key in oldProps) {
    if (!props[key]) {
      delete elm[key];
    }
  }
  for (key in props) {
    cur = props[key];
    old = oldProps[key];
    if (old !== cur && (key !== "value" || elm[key] !== cur)) {
      elm[key] = cur;
    }
  }
  /* restore excursion */
  if (preserveExcursion) {
    elm.setSelectionRange(selection[0], selection[1]);
    elm.focus();
  }
}

module.exports = {create: updateProps, update: updateProps};
```

**Comment by paldepind** [comment]
I agree that it would be nice if the props module automatically implemented this more intuitive behavior.

If I understand correctly you check `props.selectionStart` and `props.selectionEnd` such that users can control the selection manually. Otherwise I defaults to preserving the existing cursor position.

As far as I can tell this might still result in odd behavior. For instance if `values` is `more|text` (where `|` is the cursor position) and it is changed to `somemoretext`. Then the result would be ``some|moretext` because the cursor index is preserved. However fixing that would probably end up being too complex.

Would you like to submit a PR?

**Comment by katyo** [comment]
Yes, we may provide selectionStart/End properties when we need to change value to correctly set cursor position in this case.

In outline we have a big problem when value was changed by user and by application in same time. In other words, when rate of user input is higher of application response rate, we have situation, when my solution is not so good, as desired. For example, I developed custom text fields, which modifies user input by removing not allowed characters. In some cases my solution isn't still good.

Maybe one of possible solution is changing of value indirectly by sending modification commands (like `contentaeditable`).

**Comment by garth** [comment]
@katyo I just submitted a PR that fixes part of this issue. For it to work you need to be sure that your change event is synchronous.

Is for the async updates, would it possible to control the selectionStart/end via your app allways passing these as props?

If you keep the props in sync in your controller then it should work between renders. Although it may be necessary to set these every time even when not changed between old and new vnodes. Would need some testing to prove.

**Comment by paldepind** [comment]
Closing this under the assumption that @garth's PR was sufficient to solve this issue. Feel free to reopen if that is not the case.
