### ISSUE TITLE
The invocation of insert/remove hooks

### ISSUE THREAD

**Issue by katyo** [paldepind/snabbdom#65]
I tried to use `insert` hook with `canvas` node in order to initialize size (using parent node width and aspect ratio) and draw. But I found that I can't do it because `insert` (and `remove`) hook actually does not invoked on each vnode when subtree had inserted to DOM.
I don't sure about that behavior is bug or feature. But determining what node would be really inserted or removed is a non-trivial task and breaks some aspects of component-based development.
Is there any simple workarounds for this issue?
The first idea: Implement plugin, which defines `insert`/`remove` hooks, which invokes this hooks for all children of current vnode up to end-vnodes of vtree.
The second idea: Change core in same way.

**Comment by katyo** [comment]
It seems that `insert`/`remove` hooks invoked only for vnodes not for modules. Okay, so I can do my things here.

**Comment by paldepind** [comment]
> It seems that `insert`/`remove` hooks invoked only for vnodes not for modules. Okay, so I can do my things here.

Yes. That is correct. We're you trying to modify the behavior of all `canvas` elements?

**Comment by katyo** [comment]
No, I just created component to plot graphs using canvas. I used `insert`/`remove` hooks to set/unset reference to `canvas` node, and trigger initial draw. It works as desired. Thanks.

**Comment by paldepind** [comment]
Great :) In that case you shouldn't need to use a module.
