### ISSUE TITLE
'mounted' hook

### ISSUE THREAD

**Issue by AlexGalays** [paldepind/snabbdom#73]
is there such a thing? One thing I absolutely hate about virtual-dom compared to React is that there is no proper hook for "the element was newly mounted, and was inserted in the document"; this is very useful when you want to do things like measurements or anything that can't work while the element is detached.
And doing setTimeout, setImmediate, requestAnimationFrame or whatever are crazy hacks where the UI can flicker and open you to race conditions.

**Comment by AlexGalays** [comment]
It appears 'insert' does exactly that; Well done.

**Comment by avesus** [comment]
@AlexGalays thank you! You've created excellent part of documentation in
the form of true FAQ! Appreciate your research!

-- 
Best Regards,
Ivan Borisenko
