### ISSUE TITLE
How to get pointer to real element.

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [paldepind/snabbdom#78]
How can you get pointer to the real DOM element. 

There are some libraries out there like GSAP and velocity ( animation ) that are useful. 

however their api requires access to the real DOM element. 

is it possible to do it with snabbdom ?

**Comment by TylorS** [comment]
You can use hooks to accomplish this. Documentation is found [here](https://github.com/paldepind/snabbdom#hooks)

Anywhere that you are given access to `vnode` after the `create` hook is called you will have access to the real element at `vnode.elm`.

**Comment by hville** [comment]
I had he same question before and found the answer through similar issues discussions. The problem is that nowhere in the documentation the structure of the vnode is discussed. One has to read the source code to learn about `vnode.elm`

**Comment by TylorS** [comment]
I think it would be a very welcomed addition to the documentation to add a section on what makes up a snabbdom VNode.

**Comment by paldepind** [comment]
@TylorS I agree. I'll reopen this issue as a problem with the docs.

**Comment by TylorS** [comment]
# Virtual Node
**Properties**
 - [sel](#sel) 
 - [data](#data)
 - [children](#children)
 - [text](#text)
 - [elm](#elm)
 - [key](#key)

#### sel : String
The `.sel` property of a virtual node is the CSS selector passed to `h()` during creation.
For example: `h('div#container, {}, [...])` will create a a virtual node which has `div#container` as it's `.sel` property.

#### data : Object
The `.data` property of a virtual node is the place to add information for [modules](https://github.com/paldepind/snabbdom#modules-documentation) to access and manipulate the real DOM element when it is created; Add styles, CSS classes, attributes, etc.

The data object is the (optional) second parameter to `h()` 

For example `h('div', {props: {className: 'container'}, [...]}` will produce a virtual node with
```js
{
  "props": {
    className: "container"
  }
}
```
as it's `.data` object.

#### children : Array<VNode>
The `.children` property of a virtual node is the third (optional) parameter to `h()` during creation.
`.children` is simply and Array of virtual nodes that should be added as children of the parent DOM node upon creation.

For example `h('div', {}, [ h('h1', {}, 'Hello, World') ])` will create a virtual node with 
```js
[
 {
   sel: 'h1', 
   data: {}, 
   children: undefined, 
   text: 'Hello, World', 
   elm: Element,
   key: undefined,
 }
]
```
as it's `.children` property.

#### text : string
The `.text` property is created when the a virtual node is created with only a single child that possesses text and only requires `document.createTextNode()` to be used.

For example: `h('h1', {}, 'Hello')` will create a virtual node with `Hello` as it's `.text` property.

#### elm : Element

The `.elm` property of a virtual node is a pointer to the real DOM node created by snabbdom. This property is very useful to do calculations in [hooks](insert link to hooks) as well as [modules](https://github.com/paldepind/snabbdom#modules-documentation).

#### key : string | number

The `.key` property is created when a key is provided inside of your [`.data`](#data) object. The `.key` property is used to keep pointers to DOM nodes that existed previously to avoid recreating them if it is unnecessary. This is very useful for things like list reordering. A key much be either a string or a number to allow for proper lookup as it is stored internally as a key value pair inside of an object, where `.key` is the key and the value is the [`.elm`](#elm) property created.

For example: `h('div', {key: 1}, [])` will create a virtual node object with a `.key` property with the value of `1`.


All off the top of my head, I'm not 100% about all of the specifics, or if they're the best of descriptions. Hopefully it's a start and we can collaborate to make it better.

**Comment by JoyKrishnaMondal** [comment]
Thanks ! 

One final question - does VNode.elm value change over time ?

**Comment by TylorS** [comment]
My gut feeling is no, but I could be wrong; @paldepind might be able to confirm that. However take a look at the [hooks](https://github.com/paldepind/snabbdom#hooks), and in particular ones like `update()` it gets the oldVnode and the newest vnode so you're able to get the changes that occur on a particular element as well as what changed between vnodes.

**Comment by paldepind** [comment]
Snabbdom does not change `elm` after setting it.

The above description is really nice @TylorS. I definitely think it should be added to the documentation.

**Comment by TylorS** [comment]
I'll take the time to make PR soon. Is there anything you feel I missed?
