### ISSUE TITLE
Is it possible to add functionality for generator functions 

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [paldepind/snabbdom#79]
I am using a technique that makes use of generator functions. 

It would he helpful if the code below: 

```
function arrInvoker(arr) {
  return function() {
    // Special case when length is two, for performance
    arr.length === 2 ? arr[0](arr[1]) : arr[0].apply(undefined, arr.slice(1));
  };
}
```

would be changed to not give this error:

`Uncaught TypeError: Method [Generator].prototype.next called on incompatible receiver undefined`

I am doing something like this:
```
click:Component.next
```

best wishes !

**Comment by paldepind** [comment]
Correct me if I'm wrong but isn't this fixed by doing `Component.next.bind(Component)` similarly to what you'd have to do if you where using `addEventListener`?

**Comment by JoyKrishnaMondal** [comment]
not sure, but it doesn't matter anymore - since generators functions are terrible for creating components - they have way too many internal state and you need to make sure to run your next in order. 

Closures - even though are unfancy and old - will beat generation functions for abstracting components. 

Thanks @paldepind !
