### ISSUE TITLE
VNodes can't have both text content and children properties

### ISSUE THREAD

**Issue by chrisdotcode** [paldepind/snabbdom#82]
In the current implementation, it seems that having `.text` and `.children` are mutually exclusive. The current code is:

```js
if (is.array(children)) {
    ...
} else if (is.primitive(vnode.text)) {
    api.appendChild(elm, api.createTextNode(vnode.text));
}
```

Since text content is technically the first node (a text node) child of an element, I think it should instead be more like:

```js
if (is.primitive(vnode.text)) {
    api.appendChild(elm, api.createTextNode(vnode.text));
}
if (is.array(children)) {
    ...
} 

```

Will PR if approved.

**Comment by leeoniya** [comment]
`textNode` uniformity has significant performance implications.

`parentNode.firstChild.nodeValue = ...`
is ~15% faster than
`parentNode.textContent = ...`
which is > 100% faster than
`parentNode.appendChild(textNode)`

I know this because I went through the same process in domvm[1]: "Why not make the internal impl uniform". Needless to say, that experimental branch did not survive the perf regressions.

[1] https://github.com/leeoniya/domvm

**Comment by chrisdotcode** [comment]
So how about an additional conditional between `.nodeValue = ...` and `.textContent = ...`? I'd say API uniformity is worth far more than the extra cost of evaluating a single brahc.

**Comment by leeoniya** [comment]
right. the external api should be uniform. conditionals are cheap.

**Comment by paldepind** [comment]
@leeoniya So if I understand you correctly the way Snabbdom currently does it is not the fastest way? We should replace `node.textContent` with `node.firstChild.nodeValue`?

@chrisdotcode 

The text property is used if you create a vnode like this `h('a', {...}, 'Click me')`. I.e. in the case where the entire content is text. They should never be set at the same time. If you want text and other child elements you can do `h('div', ['Some text', aVnode, 'more text'])`.

**Comment by leeoniya** [comment]
@paldepind yep.

if node contains only text set `node.textContent` during initial creation and `node.firstChild.nodeValue` during patching.

**Comment by chrisdotcode** [comment]
> They should never be set at the same time.

@paldepind Yes, that's what I'm asking about. In my nicety to not make them mutually exclusive: that is, why *can't* we make it possible such that `.text` and `.children` can be set at the time time? As noted above, it's just a change in the conditional I posted above, and another conditional using `node.textContent` if there is text content during node diffing.

**Comment by leeoniya** [comment]
btw, domvm does use `createTextNode` when there is no other option, like when there are sibling nodes. but the patching is still done using `nodeValue`. aside from some conditionals in handling some special cases for optimization (textContent/nodeValue) , text nodes are no differe than normal nodes. i dunno about snabbdom's internals, but it shouldnt be particularly difficcult to implement.

**Comment by paldepind** [comment]
> @paldepind Yes, that's what I'm asking about. It would be nice if they were not mutually exclusive: that is, why *can't* we make it possible such that `.text` and `.children` can be set at the time time? As noted above by me and @leeoniya it's just a change to one or two conditionals.

Because it is unnecessary.  If you want an element with both text nodes and elements as children you can do something like this: `h('div', ['Some text', aVnode, 'more text'])`. The `text` property handles the special case where an element has only a single text node as a child.

**Comment by chrisdotcode** [comment]
I think this would be a welcome change, but you've already decided.

Thanks anyway.

**Comment by paldepind** [comment]
Cain you explain what your use case is?

**Comment by chrisdotcode** [comment]
Well, as of now, the API is inconsistent: if it's children or text, then the two should maybe occupy the same parameter like so:

```js
VNode('div', 'textContent')
or
VNode('div', [ ... children ...])
```js

As of now, it's a gotcha that you can *specify* both text and children, like this:

```js
VNode('div', 'textContent', [ ... children ...])
```

It makes it seem as if both will be utilized, when text is ignored if there are children present. My solution was that both could be present, but if not, how about the above solution: in that either text or children is specified in the same parameter?
