### ISSUE TITLE
Simplifying API (settings props, content)

### ISSUE THREAD

**Issue by whitecolor** [paldepind/snabbdom#83]
`virtual-dom` api seems a little bit simplier in some cases for example:

1) Alloing props directly without need of `props` 
`image({value: 'text'})` vs `image({props: {value: 'text'}})`

2) Element content can be not array
`div('.cls', 'Some content')` vs `div('.cls', ['Some content'])`

is it by intention you do not simplify the API?

**Comment by paldepind** [comment]
1/ Snabbdom is modular. If properties where kept at the top level like `{value: 'text'}` there'd be no way for modules to know which properties they should deal with. Should `value` be set by the property module or the attribute module? Currently each module uses one property on the data object. But if you wanted to there'd be nothing stopping you from not using the default modules and create a new module that sets properties directly from the data object.
2/ You can do that in Snabbdom as well.

**Comment by whitecolor** [comment]
Right, about second case I mean:
`div('.cls', span('Some content'))` vs `div('.cls', [span('Some content')])`
first seem not to work with snabbdom

**Comment by hville** [comment]
FYI I am currently experimenting with a small `h` wrapper with the following syntax: `h(selector, properties, children, options`) to have an API that could work with multiple vdom libraries and based on the fact that you can do pretty much everything with the props module alone and only use the option field on specific cases where optimization is desired. To be honest, I am still not sure it is a good idea.

**Comment by chrisdotcode** [comment]
@hville You can check out my [lmth](https://github.com/chrisdotcode/lmth) package which can generate DOM nodes from DSL in a manner similar to (h)yperscript. As expected, these DOM nodes can be used in whatever library uses DOM nodes.

**Comment by hville** [comment]
@chrisdotcode Thanks. I was more looking for a way to define and nest components without being too locked into the rendering engine. i.e.
`c(selector, attributes, children, options) => component`
`h(selector|component, attributes, children, options) => vdom`
`v(selector|component, attributes, children, options) => (val, key) => vdom`

`components` are just a collection of the same parameters (`selector, attributes, children, options`)
`children` can be a mixed array of text, vdom objects or components
`options` contains the special library parameters (e.g. `on`, `class`, ... for snabbdom)
`options` also contains an optional `.child` function to hydrate nested components 

In the end, I've opted to keep things simple and revert to the snabbdom `selector, data, children` pattern and see where it goes before introducing additional complexity.

**Comment by paldepind** [comment]
> Right, about second case I mean:
`div('.cls', span('Some content'))` vs `div('.cls', [span('Some content')])`
first seem not to work with snabbdom, have to wrap it with array

Yes. That is correct. I prefer to avoid overloading. Passing a string is supported because then we can just set the text content.
