### ISSUE TITLE
exposing vtree traversal methods

### ISSUE THREAD

**Issue by thurt** [paldepind/snabbdom#87]
Hello--

I would like to add a new vnode into an existing vtree, however, the location where the new vnode is to be inserted will be determined at run time ~~ this determination method is non-normative and will depend on dynamic, application-related factors.

I'm assuming snabbdom is already traversing vtree in order to do it's work when patching DOM. I'm wondering if there might be a way to hook into these traversal capabilities for dynamic vnode insertion purpose ?

Thank you for your ideas/comments

**Comment by thurt** [comment]
My thoughts: I could create my own search/traversal methods since I have a reference to every vnode as well as the composed vtree. However, it thought it seemed egregious to recreate what snabbdom is already doing, right ?

**Comment by thurt** [comment]
My intended procedure follows:
1. User clicks a "new" button
2. a new vnode is created which must be inserted after a particular vnode data signature (or inserted after some x accumulator measure)
3. the vtree is traversed until the data signature has been found/fulfilled
4. once found, the new vnode is inserted as a child of the current vnode
5. traversal bails out

**Comment by thurt** [comment]
I have looked at snabbdom.js source a little bit...the traversal mechanism appears to be intertwined with patchVnode(). So I don't think there is a clean way to make snabbdom traverse a vtree--not without running all the patching checks/procedures at the same time.

**Comment by thurt** [comment]
I was thinking that I could write a snabbdom module which is a listener for the `update` hook. Once the module finds/fulfills it's target search signature, it could add a new child vnode to the current vnode provided by the `update` event.

two problems:
1. it is not clear to me whether `update` is actually fired for every vnode (even if no changes) ?
2. it is not clear to me whether a newly inserted vnode would actually get into DOM in the same patch cycle (a ref to the children object is put into a variable before `update` is fired--so that prob. means the new vnode would not show up until after a second patch...)

**Comment by thurt** [comment]
I think this is an apt description on the problem I have with snabbdom's traversal mechanism:
> Visitor patterns use two classes -- the visitor itself and the class performing the traversal... The visitor applies its logic to a node it receives from the traversal class. Traversal classes are initialized with concrete visitor objects before the beginning of traversals...

> The downside of the visitor pattern is that the visitor's interface is not extensible. It is fully controlled by the traversal class and takes only those parameters that the traversal class passes. So, if the logic of tree processing requires additional information not provided by a traversal class or a tree node itself, the visitor class needs to have state (member) objects that should be initialized before the traversal begins. Because the visitor interface is usually implemented by a separate class, encapsulation may potentially be weakened. The "one class for each distinct type of tree processing" requirement can also lead to the creation of numerous classes that are too granular.

And the proposed solution pattern:

> The iterator pattern is simpler and its pervasive use in collection class libraries makes it one of the best-known design patterns. Tree iterators do not impose limitations on calling programs. The calling program only needs to call the iterator's next (sometimes called "advance") method.

> Another advantage of the iterator pattern is that tree-like structures can be viewed simply as another type of collection, similar to the list or Java Vector class. The iterator pattern, not visitor, is the easiest way to traverse a collection. After all, a visitor is not normally used with lists, so why use it for a tree? Given that, iterator is a better choice of a design pattern for generic algorithms.

What do you think ?

**Comment by paldepind** [comment]
Hello @thurt. I'm sorry for the late response. I completely missed this issue :disappointed:

Normally one does stuff during Snabbdoms traversal by using one of the hooks. I'm wondering if any of those would be useful in you situation?

**Comment by thurt** [comment]
Hi @paldepind This was an idea that I think snabbdom is simply not designed to do!

I basically wanted to perform modifications on the vtree before getting any DOM side-effects. The modification would be based on fulfilling a data signature defined by the end user--ex: "insert a new vnode after the 5th vnode of this type signature."

However, it looks like snabbdom uses its own "closed" iteration mechanism on the vtree, and it only notifies its "visitor" modules about changed vnodes in relation to the previous vtree. So I have no clear way of accessing unchanged vnodes, whose data I need to check to fulfill the user-defined data signature.

my solution has been to traverse my in-memory vtree with my own breadth-first search iterator of parent-to-child vnodes. After performing my custom traversal/transformation, I send the vtree to snabbdom's patch.

Do you think this is the best approach ?

**Comment by paldepind** [comment]
> I basically wanted to perform modifications on the vtree before getting any DOM side-effects.

Snabbdom modifies the DOM while traversing. So you are indeed right that if you want to do a traversal before any DOM effects then you can't use hooks.

Traversing the virtual tree is quite simple. And it sounds like what you want to do has to be done in a kind of preprocessing traversal. So I do think it is the best approach.

**Comment by thurt** [comment]
Thanks, appreciate your input @paldepind -- closing this issue now
