### ISSUE TITLE
Root element is not rendering

### ISSUE THREAD

**Issue by ismail-codar** [paldepind/snabbdom#9]
Hyperscript's root element is not rendering allways. Because snabbdom.js line 184 ... oldCh = oldVnode.children, ch = vnode.children;......

Problem:
```javascript
 var vnode = h('div#id.two.classes', [
        h('span', 'This is text')
    ]);
    patch(document.getElementById('container'), vnode);
```
output as
```html
<div id="container"><span>This is text</span></div>
```
But may be:
```html
<div id="container"><div id="id" class="two classes"><span>This is text</span></div></div>
```

**Comment by paldepind** [comment]
If I understand this correctly it is the same thing that @raine recently brought up in the Gitter room.

Basically Snabbdom does not apply the information found in the selector for the root vnode. It assumes that that information is already correct. The solution is to make sure that the assumption is correct.

**Comment by raine** [comment]
Needs to be documented.

**Comment by paldepind** [comment]
> Needs to be documented.

I certainly agree!

Another option is to create a new element based on the root vnode when `patch` is initially run against a raw element and then replace the raw element with the created root element. I like to have behavior that is intuitive and doesn't surprise people. The only bad thing about doing that is that after `patch` the DOM element passed to `patch` would no longer be in the DOM. But if you really need it you could easily dig it out of the vnode returned by `patch`.

**Comment by ismail-codar** [comment]
On above example root is meant to "div#id.two.classes" not the "#container" element.  It may be misunderstood. 

In the rendering output div#id.two.classes information disappears. 
In this case, users can manage itself but normally users waits to:

h('div#myId.myClass', ['This is text']) => <div id="myId" class="myClass">This is text</div> but snabbdom only outputs => This is text

**Comment by paldepind** [comment]
> On above example root is meant to "div#id.two.classes" not the "#container" element. It may be misunderstood. 

I think so. The element passed to `patch` should be an empty element matching the root vnode. So you should do this:

```javascript
patch(document.getElementById('id'), vnode);
```

Is that unclear in the documentation?

**Comment by ismail-codar** [comment]
https://github.com/paldepind/snabbdom#inline-example seems contrary to this strategy. id = container element is not matching to root vnode (h('div#id.two.classes'....)

**Comment by paldepind** [comment]
I've now done this:

* Implemented the [behavior described here](https://github.com/paldepind/snabbdom/issues/9#issuecomment-116083546). This should be more expectable.
* Updated the inline example. It was indeed confusing and misleading.
* Updated the [documentation of `patch`](https://github.com/paldepind/snabbdom#patch). This should clarify this as well as the fact that vnode's will have to be reused.

@ismail-codar and @raine, does this solve the issues and is the documentation clear enough now? Please let me know if this is still not adequate.

**Comment by ismail-codar** [comment]
Quite enough. :+1:

**Comment by avesus** [comment]
I absolutely disagree with idea that `h('div#myId.myClass', ['This is text'])` should become `<div id="myId" class="myClass">This is text</div>`
Things specified in first argument are _selector_, but I've no complete understanding of such selectors at all because of hierarchical JSX Components idea. Is it possible to create _true_ component wrapper to allow snabbdom to behave like React Components?

**Comment by paldepind** [comment]
@avesus 

> Things specified in first argument are selector

The first argument to `h` is not a selector. It's a description of the element including its tag name, its id and it's static classes.

> Is it possible to create true component wrapper to allow snabbdom to behave like React Components?

I certainly think it is possible to build such a thing on top of Snabbdom.
