### ISSUE TITLE
dataset module

### ISSUE THREAD

**Issue by hville** [paldepind/snabbdom#90]
**Summary - tl;dr**
I'm currently using a tiny and trivial `dataset` module and I am wondering if it is worth sharing (tiny size but limited benefits). I can prepare a PR with tests if there is any interest and/or recommendations.

**Background**
Because the `node.dataset` property is read-only, using `{props: {dataset: {foo: 'foo'}}}` does not work. The attributes module can be used but wrapping the attribute names get a little tedious: `{attrs: {'data-foo': foo}}`. The little module below allows for a new `dataset` item in the `data` object so that we can write: `{dataset: {foo: 'foo'}}`.

```
function updateDataset(oldVnode, vnode) {
  var key
  var elm = vnode.elm
  var oldDataset = oldVnode.data.dataset || {}
  var dataset = vnode.data.dataset || {}

  for (key in oldDataset) if (!dataset[key]) delete elm.dataset[key]
  for (key in dataset) if (oldDataset[key] !== dataset[key]) elm.dataset[key] = dataset[key]
}
module.exports = {create: updateDataset, update: updateDataset}
```

**Use Case**
Works nicely for event handlers where we can update a `data-action` parameter instead of recreating a function specific to every elements. In my case, I use it to store the origin JSONPointer in `data-path` so that the event handler can produce a JSONPatch. Example: 

```    
function commonHandler(e) {  //same handler declared once for all element on every render
  store.patch([{
    op: 'replace', 
    path: e.target.dataset.path, 
    value: e.target.value  // ommitting additional formatting and validation
  }])
}
vtree = h('input', {
  props: {
    value: store.get().foo.bar.baz,
    oninput: commonHandler
  },
  dataset: {path: '/foo/bar/baz'} //same outcome as attrs:{'data-path': '/foo/bar/baz'}
})
```

Both `{attrs: {'data-foo': foo}}` and `{dataset: {foo: 'foo'}}` modify the underlying HTML so I am not sure if it is not be better to simply use some random custom property instead: `{props: {datasetfoo: 'foo'}}`.

Feedback/suggestions welcome

**Comment by TylorS** [comment]
I definitely think this is a useful addition to the currently offered modules. I have been using `attrs: {'data-x': 1} ` as well and it's not the best. In the name of performance only, which many doesn't matter all that much considering most people probably don't have more than a few dataset attributes to set, I've modified your code just a smidge to use regular for-loops + Object.keys() which is significantly faster in v8 - source for that claim is [here](https://jsperf.com/object-keys-vs-for-in-with-closure/114)

```js
function updateDataset(oldVnode, vNode) {
  var elm = vNode.elm
  var oldDataset = oldVNode.data.dataset || {}
  var dataset = vNode.data.dataset || {}

  var oldKeys = Object.keys(oldDataSet)
  var keys = Object.keys(dataset)
  
  for (var i = 0; i < oldKeys.length; ++i) {
    if (!dataset[oldKeys[i]]) {
     delete elm.dataset[key] 
    }
  }

  for(var i =0; i < keys.length; ++i) {
    var key = keys[i]
    oldKeyIndex = oldKeys.findIndex(key)
    if (oldKeyIndex !== -1 && oldDataset[oldKeyIndex] !== dataset[key]) {
      elm.dataset[key] = dataset[key]
    }
  }
}
```

**Comment by hville** [comment]
Thanks for the feedback. I've used `for-in` to match the structure and style of the other modules. The loop optimization could be a separate PR for all modules.

I also don't understand your intent in the second last line:
`if (oldKeyIndex !== -1 && oldDataset[oldKeyIndex] !== dataset[key]) { ...`
What is wrong with the former `if (oldDataset[key] !== dataset[key]) { ...`?

**Comment by TylorS** [comment]
Good catch, I think I may have screwed that up a bit. Basically the oldKeyIndex might return as -1 because it didn't previously exist. It should probably be
```js
if (oldKeyIndex === -1 || oldDataset[oldKeyIndex] !== dataset[key]) {...}
```

Does that make more sense?
