### ISSUE TITLE
What is the key property for ?

### ISSUE THREAD

**Issue by thurt** [paldepind/snabbdom#92]
Hello,

I see that vnode.js extracts key from data.key
and in snabbdom.js, key is used for checking if same vnode
```javascript
function sameVnode(vnode1, vnode2) {
  return vnode1.key === vnode2.key && vnode1.sel === vnode2.sel;
}
```

I don't really understand the use case for key? In what scenarios would I want to set data.key in my h constructs? ~~Thanks

**Comment by hville** [comment]
It is for arrays of children. The index may have changed (new sort, splice or shift) but the node is the same. `key` is used to assign a unique id within the array, independent of the index.

**Comment by paldepind** [comment]
Yes. If you reorder element then the `key` property is used to figure out which element moved where.

**Comment by thurt** [comment]
Thanks!

I'm wondering: if i assign unique keys to sortable children, does this also
mean that snabbdom can more efficiently handle patching when they are
sorted?
Le 28 mars 2016 08:21, "Simon Friis Vindum" <notifications@github.com> a
écrit :

**Comment by thurt** [comment]
Thanks @paldepind @hville -- I looked at the source code a little bit more and this makes sense now with your commentary
